/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: geyser.proto */

#ifndef PROTOBUF_C_geyser_2eproto__INCLUDED
#define PROTOBUF_C_geyser_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif

#include "google/protobuf/timestamp.pb-c.h"
#include "solana-storage.pb-c.h"

typedef struct Geyser__SubscribeRequest Geyser__SubscribeRequest;
typedef struct Geyser__SubscribeRequest__AccountsEntry Geyser__SubscribeRequest__AccountsEntry;
typedef struct Geyser__SubscribeRequest__SlotsEntry Geyser__SubscribeRequest__SlotsEntry;
typedef struct Geyser__SubscribeRequest__TransactionsEntry Geyser__SubscribeRequest__TransactionsEntry;
typedef struct Geyser__SubscribeRequest__TransactionsStatusEntry Geyser__SubscribeRequest__TransactionsStatusEntry;
typedef struct Geyser__SubscribeRequest__BlocksEntry Geyser__SubscribeRequest__BlocksEntry;
typedef struct Geyser__SubscribeRequest__BlocksMetaEntry Geyser__SubscribeRequest__BlocksMetaEntry;
typedef struct Geyser__SubscribeRequest__EntryEntry Geyser__SubscribeRequest__EntryEntry;
typedef struct Geyser__SubscribeRequestFilterAccounts Geyser__SubscribeRequestFilterAccounts;
typedef struct Geyser__SubscribeRequestFilterAccountsFilter Geyser__SubscribeRequestFilterAccountsFilter;
typedef struct Geyser__SubscribeRequestFilterAccountsFilterMemcmp Geyser__SubscribeRequestFilterAccountsFilterMemcmp;
typedef struct Geyser__SubscribeRequestFilterAccountsFilterLamports Geyser__SubscribeRequestFilterAccountsFilterLamports;
typedef struct Geyser__SubscribeRequestFilterSlots Geyser__SubscribeRequestFilterSlots;
typedef struct Geyser__SubscribeRequestFilterTransactions Geyser__SubscribeRequestFilterTransactions;
typedef struct Geyser__SubscribeRequestFilterBlocks Geyser__SubscribeRequestFilterBlocks;
typedef struct Geyser__SubscribeRequestFilterBlocksMeta Geyser__SubscribeRequestFilterBlocksMeta;
typedef struct Geyser__SubscribeRequestFilterEntry Geyser__SubscribeRequestFilterEntry;
typedef struct Geyser__SubscribeRequestAccountsDataSlice Geyser__SubscribeRequestAccountsDataSlice;
typedef struct Geyser__SubscribeRequestPing Geyser__SubscribeRequestPing;
typedef struct Geyser__SubscribeUpdate Geyser__SubscribeUpdate;
typedef struct Geyser__SubscribeUpdateAccount Geyser__SubscribeUpdateAccount;
typedef struct Geyser__SubscribeUpdateAccountInfo Geyser__SubscribeUpdateAccountInfo;
typedef struct Geyser__SubscribeUpdateSlot Geyser__SubscribeUpdateSlot;
typedef struct Geyser__SubscribeUpdateTransaction Geyser__SubscribeUpdateTransaction;
typedef struct Geyser__SubscribeUpdateTransactionInfo Geyser__SubscribeUpdateTransactionInfo;
typedef struct Geyser__SubscribeUpdateTransactionStatus Geyser__SubscribeUpdateTransactionStatus;
typedef struct Geyser__SubscribeUpdateBlock Geyser__SubscribeUpdateBlock;
typedef struct Geyser__SubscribeUpdateBlockMeta Geyser__SubscribeUpdateBlockMeta;
typedef struct Geyser__SubscribeUpdateEntry Geyser__SubscribeUpdateEntry;
typedef struct Geyser__SubscribeUpdatePing Geyser__SubscribeUpdatePing;
typedef struct Geyser__SubscribeUpdatePong Geyser__SubscribeUpdatePong;
typedef struct Geyser__SubscribeReplayInfoRequest Geyser__SubscribeReplayInfoRequest;
typedef struct Geyser__SubscribeReplayInfoResponse Geyser__SubscribeReplayInfoResponse;
typedef struct Geyser__PingRequest Geyser__PingRequest;
typedef struct Geyser__PongResponse Geyser__PongResponse;
typedef struct Geyser__GetLatestBlockhashRequest Geyser__GetLatestBlockhashRequest;
typedef struct Geyser__GetLatestBlockhashResponse Geyser__GetLatestBlockhashResponse;
typedef struct Geyser__GetBlockHeightRequest Geyser__GetBlockHeightRequest;
typedef struct Geyser__GetBlockHeightResponse Geyser__GetBlockHeightResponse;
typedef struct Geyser__GetSlotRequest Geyser__GetSlotRequest;
typedef struct Geyser__GetSlotResponse Geyser__GetSlotResponse;
typedef struct Geyser__GetVersionRequest Geyser__GetVersionRequest;
typedef struct Geyser__GetVersionResponse Geyser__GetVersionResponse;
typedef struct Geyser__IsBlockhashValidRequest Geyser__IsBlockhashValidRequest;
typedef struct Geyser__IsBlockhashValidResponse Geyser__IsBlockhashValidResponse;


/* --- enums --- */

typedef enum _Geyser__CommitmentLevel {
  GEYSER__COMMITMENT_LEVEL__PROCESSED = 0,
  GEYSER__COMMITMENT_LEVEL__CONFIRMED = 1,
  GEYSER__COMMITMENT_LEVEL__FINALIZED = 2
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEYSER__COMMITMENT_LEVEL)
} Geyser__CommitmentLevel;
typedef enum _Geyser__SlotStatus {
  GEYSER__SLOT_STATUS__SLOT_PROCESSED = 0,
  GEYSER__SLOT_STATUS__SLOT_CONFIRMED = 1,
  GEYSER__SLOT_STATUS__SLOT_FINALIZED = 2,
  GEYSER__SLOT_STATUS__SLOT_FIRST_SHRED_RECEIVED = 3,
  GEYSER__SLOT_STATUS__SLOT_COMPLETED = 4,
  GEYSER__SLOT_STATUS__SLOT_CREATED_BANK = 5,
  GEYSER__SLOT_STATUS__SLOT_DEAD = 6
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEYSER__SLOT_STATUS)
} Geyser__SlotStatus;

/* --- messages --- */

struct  Geyser__SubscribeRequest__AccountsEntry
{
  ProtobufCMessage base;
  char *key;
  Geyser__SubscribeRequestFilterAccounts *value;
};
#define GEYSER__SUBSCRIBE_REQUEST__ACCOUNTS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request__accounts_entry__descriptor) \
    , NULL, NULL }


struct  Geyser__SubscribeRequest__SlotsEntry
{
  ProtobufCMessage base;
  char *key;
  Geyser__SubscribeRequestFilterSlots *value;
};
#define GEYSER__SUBSCRIBE_REQUEST__SLOTS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request__slots_entry__descriptor) \
    , NULL, NULL }


struct  Geyser__SubscribeRequest__TransactionsEntry
{
  ProtobufCMessage base;
  char *key;
  Geyser__SubscribeRequestFilterTransactions *value;
};
#define GEYSER__SUBSCRIBE_REQUEST__TRANSACTIONS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request__transactions_entry__descriptor) \
    , NULL, NULL }


struct  Geyser__SubscribeRequest__TransactionsStatusEntry
{
  ProtobufCMessage base;
  char *key;
  Geyser__SubscribeRequestFilterTransactions *value;
};
#define GEYSER__SUBSCRIBE_REQUEST__TRANSACTIONS_STATUS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request__transactions_status_entry__descriptor) \
    , NULL, NULL }


struct  Geyser__SubscribeRequest__BlocksEntry
{
  ProtobufCMessage base;
  char *key;
  Geyser__SubscribeRequestFilterBlocks *value;
};
#define GEYSER__SUBSCRIBE_REQUEST__BLOCKS_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request__blocks_entry__descriptor) \
    , NULL, NULL }


struct  Geyser__SubscribeRequest__BlocksMetaEntry
{
  ProtobufCMessage base;
  char *key;
  Geyser__SubscribeRequestFilterBlocksMeta *value;
};
#define GEYSER__SUBSCRIBE_REQUEST__BLOCKS_META_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request__blocks_meta_entry__descriptor) \
    , NULL, NULL }


struct  Geyser__SubscribeRequest__EntryEntry
{
  ProtobufCMessage base;
  char *key;
  Geyser__SubscribeRequestFilterEntry *value;
};
#define GEYSER__SUBSCRIBE_REQUEST__ENTRY_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request__entry_entry__descriptor) \
    , NULL, NULL }


struct  Geyser__SubscribeRequest
{
  ProtobufCMessage base;
  size_t n_accounts;
  Geyser__SubscribeRequest__AccountsEntry **accounts;
  size_t n_slots;
  Geyser__SubscribeRequest__SlotsEntry **slots;
  size_t n_transactions;
  Geyser__SubscribeRequest__TransactionsEntry **transactions;
  size_t n_transactions_status;
  Geyser__SubscribeRequest__TransactionsStatusEntry **transactions_status;
  size_t n_blocks;
  Geyser__SubscribeRequest__BlocksEntry **blocks;
  size_t n_blocks_meta;
  Geyser__SubscribeRequest__BlocksMetaEntry **blocks_meta;
  size_t n_entry;
  Geyser__SubscribeRequest__EntryEntry **entry;
  protobuf_c_boolean has_commitment;
  Geyser__CommitmentLevel commitment;
  size_t n_accounts_data_slice;
  Geyser__SubscribeRequestAccountsDataSlice **accounts_data_slice;
  Geyser__SubscribeRequestPing *ping;
  protobuf_c_boolean has_from_slot;
  uint64_t from_slot;
};
#define GEYSER__SUBSCRIBE_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0, GEYSER__COMMITMENT_LEVEL__PROCESSED, 0,NULL, NULL, 0, 0 }


struct  Geyser__SubscribeRequestFilterAccounts
{
  ProtobufCMessage base;
  size_t n_account;
  char **account;
  size_t n_owner;
  char **owner;
  size_t n_filters;
  Geyser__SubscribeRequestFilterAccountsFilter **filters;
  protobuf_c_boolean has_nonempty_txn_signature;
  protobuf_c_boolean nonempty_txn_signature;
};
#define GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_filter_accounts__descriptor) \
    , 0,NULL, 0,NULL, 0,NULL, 0, 0 }


typedef enum {
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER__FILTER__NOT_SET = 0,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER__FILTER_MEMCMP = 1,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER__FILTER_DATASIZE = 2,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER__FILTER_TOKEN_ACCOUNT_STATE = 3,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER__FILTER_LAMPORTS = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER__FILTER__CASE)
} Geyser__SubscribeRequestFilterAccountsFilter__FilterCase;

struct  Geyser__SubscribeRequestFilterAccountsFilter
{
  ProtobufCMessage base;
  Geyser__SubscribeRequestFilterAccountsFilter__FilterCase filter_case;
  union {
    Geyser__SubscribeRequestFilterAccountsFilterMemcmp *memcmp;
    uint64_t datasize;
    protobuf_c_boolean token_account_state;
    Geyser__SubscribeRequestFilterAccountsFilterLamports *lamports;
  };
};
#define GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_filter_accounts_filter__descriptor) \
    , GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER__FILTER__NOT_SET, {0} }


typedef enum {
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_MEMCMP__DATA__NOT_SET = 0,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_MEMCMP__DATA_BYTES = 2,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_MEMCMP__DATA_BASE58 = 3,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_MEMCMP__DATA_BASE64 = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_MEMCMP__DATA__CASE)
} Geyser__SubscribeRequestFilterAccountsFilterMemcmp__DataCase;

struct  Geyser__SubscribeRequestFilterAccountsFilterMemcmp
{
  ProtobufCMessage base;
  protobuf_c_boolean has_offset;
  uint64_t offset;
  Geyser__SubscribeRequestFilterAccountsFilterMemcmp__DataCase data_case;
  union {
    ProtobufCBinaryData bytes;
    char *base58;
    char *base64;
  };
};
#define GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_MEMCMP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_filter_accounts_filter_memcmp__descriptor) \
    , 0, 0, GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_MEMCMP__DATA__NOT_SET, {0} }


typedef enum {
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_LAMPORTS__CMP__NOT_SET = 0,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_LAMPORTS__CMP_EQ = 1,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_LAMPORTS__CMP_NE = 2,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_LAMPORTS__CMP_LT = 3,
  GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_LAMPORTS__CMP_GT = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_LAMPORTS__CMP__CASE)
} Geyser__SubscribeRequestFilterAccountsFilterLamports__CmpCase;

struct  Geyser__SubscribeRequestFilterAccountsFilterLamports
{
  ProtobufCMessage base;
  Geyser__SubscribeRequestFilterAccountsFilterLamports__CmpCase cmp_case;
  union {
    uint64_t eq;
    uint64_t ne;
    uint64_t lt;
    uint64_t gt;
  };
};
#define GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_LAMPORTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_filter_accounts_filter_lamports__descriptor) \
    , GEYSER__SUBSCRIBE_REQUEST_FILTER_ACCOUNTS_FILTER_LAMPORTS__CMP__NOT_SET, {0} }


struct  Geyser__SubscribeRequestFilterSlots
{
  ProtobufCMessage base;
  protobuf_c_boolean has_filter_by_commitment;
  protobuf_c_boolean filter_by_commitment;
  protobuf_c_boolean has_interslot_updates;
  protobuf_c_boolean interslot_updates;
};
#define GEYSER__SUBSCRIBE_REQUEST_FILTER_SLOTS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_filter_slots__descriptor) \
    , 0, 0, 0, 0 }


struct  Geyser__SubscribeRequestFilterTransactions
{
  ProtobufCMessage base;
  protobuf_c_boolean has_vote;
  protobuf_c_boolean vote;
  protobuf_c_boolean has_failed;
  protobuf_c_boolean failed;
  char *signature;
  size_t n_account_include;
  char **account_include;
  size_t n_account_exclude;
  char **account_exclude;
  size_t n_account_required;
  char **account_required;
};
#define GEYSER__SUBSCRIBE_REQUEST_FILTER_TRANSACTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_filter_transactions__descriptor) \
    , 0, 0, 0, 0, NULL, 0,NULL, 0,NULL, 0,NULL }


struct  Geyser__SubscribeRequestFilterBlocks
{
  ProtobufCMessage base;
  size_t n_account_include;
  char **account_include;
  protobuf_c_boolean has_include_transactions;
  protobuf_c_boolean include_transactions;
  protobuf_c_boolean has_include_accounts;
  protobuf_c_boolean include_accounts;
  protobuf_c_boolean has_include_entries;
  protobuf_c_boolean include_entries;
};
#define GEYSER__SUBSCRIBE_REQUEST_FILTER_BLOCKS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_filter_blocks__descriptor) \
    , 0,NULL, 0, 0, 0, 0, 0, 0 }


struct  Geyser__SubscribeRequestFilterBlocksMeta
{
  ProtobufCMessage base;
};
#define GEYSER__SUBSCRIBE_REQUEST_FILTER_BLOCKS_META__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_filter_blocks_meta__descriptor) \
     }


struct  Geyser__SubscribeRequestFilterEntry
{
  ProtobufCMessage base;
};
#define GEYSER__SUBSCRIBE_REQUEST_FILTER_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_filter_entry__descriptor) \
     }


struct  Geyser__SubscribeRequestAccountsDataSlice
{
  ProtobufCMessage base;
  protobuf_c_boolean has_offset;
  uint64_t offset;
  protobuf_c_boolean has_length;
  uint64_t length;
};
#define GEYSER__SUBSCRIBE_REQUEST_ACCOUNTS_DATA_SLICE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_accounts_data_slice__descriptor) \
    , 0, 0, 0, 0 }


struct  Geyser__SubscribeRequestPing
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  int32_t id;
};
#define GEYSER__SUBSCRIBE_REQUEST_PING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_request_ping__descriptor) \
    , 0, 0 }


typedef enum {
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF__NOT_SET = 0,
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF_ACCOUNT = 2,
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF_SLOT = 3,
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF_TRANSACTION = 4,
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF_TRANSACTION_STATUS = 10,
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF_BLOCK = 5,
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF_PING = 6,
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF_PONG = 9,
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF_BLOCK_META = 7,
  GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF_ENTRY = 8
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF__CASE)
} Geyser__SubscribeUpdate__UpdateOneofCase;

struct  Geyser__SubscribeUpdate
{
  ProtobufCMessage base;
  size_t n_filters;
  char **filters;
  Google__Protobuf__Timestamp *created_at;
  Geyser__SubscribeUpdate__UpdateOneofCase update_oneof_case;
  union {
    Geyser__SubscribeUpdateAccount *account;
    Geyser__SubscribeUpdateSlot *slot;
    Geyser__SubscribeUpdateTransaction *transaction;
    Geyser__SubscribeUpdateTransactionStatus *transaction_status;
    Geyser__SubscribeUpdateBlock *block;
    Geyser__SubscribeUpdatePing *ping;
    Geyser__SubscribeUpdatePong *pong;
    Geyser__SubscribeUpdateBlockMeta *block_meta;
    Geyser__SubscribeUpdateEntry *entry;
  };
};
#define GEYSER__SUBSCRIBE_UPDATE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update__descriptor) \
    , 0,NULL, NULL, GEYSER__SUBSCRIBE_UPDATE__UPDATE_ONEOF__NOT_SET, {0} }


struct  Geyser__SubscribeUpdateAccount
{
  ProtobufCMessage base;
  Geyser__SubscribeUpdateAccountInfo *account;
  protobuf_c_boolean has_slot;
  uint64_t slot;
  protobuf_c_boolean has_is_startup;
  protobuf_c_boolean is_startup;
};
#define GEYSER__SUBSCRIBE_UPDATE_ACCOUNT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_account__descriptor) \
    , NULL, 0, 0, 0, 0 }


struct  Geyser__SubscribeUpdateAccountInfo
{
  ProtobufCMessage base;
  protobuf_c_boolean has_pubkey;
  ProtobufCBinaryData pubkey;
  protobuf_c_boolean has_lamports;
  uint64_t lamports;
  protobuf_c_boolean has_owner;
  ProtobufCBinaryData owner;
  protobuf_c_boolean has_executable;
  protobuf_c_boolean executable;
  protobuf_c_boolean has_rent_epoch;
  uint64_t rent_epoch;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
  protobuf_c_boolean has_write_version;
  uint64_t write_version;
  protobuf_c_boolean has_txn_signature;
  ProtobufCBinaryData txn_signature;
};
#define GEYSER__SUBSCRIBE_UPDATE_ACCOUNT_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_account_info__descriptor) \
    , 0, {0,NULL}, 0, 0, 0, {0,NULL}, 0, 0, 0, 0, 0, {0,NULL}, 0, 0, 0, {0,NULL} }


struct  Geyser__SubscribeUpdateSlot
{
  ProtobufCMessage base;
  protobuf_c_boolean has_slot;
  uint64_t slot;
  protobuf_c_boolean has_parent;
  uint64_t parent;
  protobuf_c_boolean has_status;
  Geyser__SlotStatus status;
  char *dead_error;
};
#define GEYSER__SUBSCRIBE_UPDATE_SLOT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_slot__descriptor) \
    , 0, 0, 0, 0, 0, GEYSER__SLOT_STATUS__SLOT_PROCESSED, NULL }


struct  Geyser__SubscribeUpdateTransaction
{
  ProtobufCMessage base;
  Geyser__SubscribeUpdateTransactionInfo *transaction;
  protobuf_c_boolean has_slot;
  uint64_t slot;
};
#define GEYSER__SUBSCRIBE_UPDATE_TRANSACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_transaction__descriptor) \
    , NULL, 0, 0 }


struct  Geyser__SubscribeUpdateTransactionInfo
{
  ProtobufCMessage base;
  protobuf_c_boolean has_signature;
  ProtobufCBinaryData signature;
  protobuf_c_boolean has_is_vote;
  protobuf_c_boolean is_vote;
  Solana__Storage__ConfirmedBlock__Transaction *transaction;
  Solana__Storage__ConfirmedBlock__TransactionStatusMeta *meta;
  protobuf_c_boolean has_index;
  uint64_t index;
};
#define GEYSER__SUBSCRIBE_UPDATE_TRANSACTION_INFO__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_transaction_info__descriptor) \
    , 0, {0,NULL}, 0, 0, NULL, NULL, 0, 0 }


struct  Geyser__SubscribeUpdateTransactionStatus
{
  ProtobufCMessage base;
  protobuf_c_boolean has_slot;
  uint64_t slot;
  protobuf_c_boolean has_signature;
  ProtobufCBinaryData signature;
  protobuf_c_boolean has_is_vote;
  protobuf_c_boolean is_vote;
  protobuf_c_boolean has_index;
  uint64_t index;
  Solana__Storage__ConfirmedBlock__TransactionError *err;
};
#define GEYSER__SUBSCRIBE_UPDATE_TRANSACTION_STATUS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_transaction_status__descriptor) \
    , 0, 0, 0, {0,NULL}, 0, 0, 0, 0, NULL }


struct  Geyser__SubscribeUpdateBlock
{
  ProtobufCMessage base;
  protobuf_c_boolean has_slot;
  uint64_t slot;
  char *blockhash;
  Solana__Storage__ConfirmedBlock__Rewards *rewards;
  Solana__Storage__ConfirmedBlock__UnixTimestamp *block_time;
  Solana__Storage__ConfirmedBlock__BlockHeight *block_height;
  protobuf_c_boolean has_parent_slot;
  uint64_t parent_slot;
  char *parent_blockhash;
  protobuf_c_boolean has_executed_transaction_count;
  uint64_t executed_transaction_count;
  size_t n_transactions;
  Geyser__SubscribeUpdateTransactionInfo **transactions;
  protobuf_c_boolean has_updated_account_count;
  uint64_t updated_account_count;
  size_t n_accounts;
  Geyser__SubscribeUpdateAccountInfo **accounts;
  protobuf_c_boolean has_entries_count;
  uint64_t entries_count;
  size_t n_entries;
  Geyser__SubscribeUpdateEntry **entries;
};
#define GEYSER__SUBSCRIBE_UPDATE_BLOCK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_block__descriptor) \
    , 0, 0, NULL, NULL, NULL, NULL, 0, 0, NULL, 0, 0, 0,NULL, 0, 0, 0,NULL, 0, 0, 0,NULL }


struct  Geyser__SubscribeUpdateBlockMeta
{
  ProtobufCMessage base;
  protobuf_c_boolean has_slot;
  uint64_t slot;
  char *blockhash;
  Solana__Storage__ConfirmedBlock__Rewards *rewards;
  Solana__Storage__ConfirmedBlock__UnixTimestamp *block_time;
  Solana__Storage__ConfirmedBlock__BlockHeight *block_height;
  protobuf_c_boolean has_parent_slot;
  uint64_t parent_slot;
  char *parent_blockhash;
  protobuf_c_boolean has_executed_transaction_count;
  uint64_t executed_transaction_count;
  protobuf_c_boolean has_entries_count;
  uint64_t entries_count;
};
#define GEYSER__SUBSCRIBE_UPDATE_BLOCK_META__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_block_meta__descriptor) \
    , 0, 0, NULL, NULL, NULL, NULL, 0, 0, NULL, 0, 0, 0, 0 }


struct  Geyser__SubscribeUpdateEntry
{
  ProtobufCMessage base;
  protobuf_c_boolean has_slot;
  uint64_t slot;
  protobuf_c_boolean has_index;
  uint64_t index;
  protobuf_c_boolean has_num_hashes;
  uint64_t num_hashes;
  protobuf_c_boolean has_hash;
  ProtobufCBinaryData hash;
  protobuf_c_boolean has_executed_transaction_count;
  uint64_t executed_transaction_count;
  /*
   * added in v1.18, for solana 1.17 value is always 0
   */
  protobuf_c_boolean has_starting_transaction_index;
  uint64_t starting_transaction_index;
};
#define GEYSER__SUBSCRIBE_UPDATE_ENTRY__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_entry__descriptor) \
    , 0, 0, 0, 0, 0, 0, 0, {0,NULL}, 0, 0, 0, 0 }


struct  Geyser__SubscribeUpdatePing
{
  ProtobufCMessage base;
};
#define GEYSER__SUBSCRIBE_UPDATE_PING__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_ping__descriptor) \
     }


struct  Geyser__SubscribeUpdatePong
{
  ProtobufCMessage base;
  protobuf_c_boolean has_id;
  int32_t id;
};
#define GEYSER__SUBSCRIBE_UPDATE_PONG__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_update_pong__descriptor) \
    , 0, 0 }


struct  Geyser__SubscribeReplayInfoRequest
{
  ProtobufCMessage base;
};
#define GEYSER__SUBSCRIBE_REPLAY_INFO_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_replay_info_request__descriptor) \
     }


struct  Geyser__SubscribeReplayInfoResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_first_available;
  uint64_t first_available;
};
#define GEYSER__SUBSCRIBE_REPLAY_INFO_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__subscribe_replay_info_response__descriptor) \
    , 0, 0 }


struct  Geyser__PingRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_count;
  int32_t count;
};
#define GEYSER__PING_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__ping_request__descriptor) \
    , 0, 0 }


struct  Geyser__PongResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_count;
  int32_t count;
};
#define GEYSER__PONG_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__pong_response__descriptor) \
    , 0, 0 }


struct  Geyser__GetLatestBlockhashRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_commitment;
  Geyser__CommitmentLevel commitment;
};
#define GEYSER__GET_LATEST_BLOCKHASH_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__get_latest_blockhash_request__descriptor) \
    , 0, GEYSER__COMMITMENT_LEVEL__PROCESSED }


struct  Geyser__GetLatestBlockhashResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_slot;
  uint64_t slot;
  char *blockhash;
  protobuf_c_boolean has_last_valid_block_height;
  uint64_t last_valid_block_height;
};
#define GEYSER__GET_LATEST_BLOCKHASH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__get_latest_blockhash_response__descriptor) \
    , 0, 0, NULL, 0, 0 }


struct  Geyser__GetBlockHeightRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_commitment;
  Geyser__CommitmentLevel commitment;
};
#define GEYSER__GET_BLOCK_HEIGHT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__get_block_height_request__descriptor) \
    , 0, GEYSER__COMMITMENT_LEVEL__PROCESSED }


struct  Geyser__GetBlockHeightResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_block_height;
  uint64_t block_height;
};
#define GEYSER__GET_BLOCK_HEIGHT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__get_block_height_response__descriptor) \
    , 0, 0 }


struct  Geyser__GetSlotRequest
{
  ProtobufCMessage base;
  protobuf_c_boolean has_commitment;
  Geyser__CommitmentLevel commitment;
};
#define GEYSER__GET_SLOT_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__get_slot_request__descriptor) \
    , 0, GEYSER__COMMITMENT_LEVEL__PROCESSED }


struct  Geyser__GetSlotResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_slot;
  uint64_t slot;
};
#define GEYSER__GET_SLOT_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__get_slot_response__descriptor) \
    , 0, 0 }


struct  Geyser__GetVersionRequest
{
  ProtobufCMessage base;
};
#define GEYSER__GET_VERSION_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__get_version_request__descriptor) \
     }


struct  Geyser__GetVersionResponse
{
  ProtobufCMessage base;
  char *version;
};
#define GEYSER__GET_VERSION_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__get_version_response__descriptor) \
    , NULL }


struct  Geyser__IsBlockhashValidRequest
{
  ProtobufCMessage base;
  char *blockhash;
  protobuf_c_boolean has_commitment;
  Geyser__CommitmentLevel commitment;
};
#define GEYSER__IS_BLOCKHASH_VALID_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__is_blockhash_valid_request__descriptor) \
    , NULL, 0, GEYSER__COMMITMENT_LEVEL__PROCESSED }


struct  Geyser__IsBlockhashValidResponse
{
  ProtobufCMessage base;
  protobuf_c_boolean has_slot;
  uint64_t slot;
  protobuf_c_boolean has_valid;
  protobuf_c_boolean valid;
};
#define GEYSER__IS_BLOCKHASH_VALID_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&geyser__is_blockhash_valid_response__descriptor) \
    , 0, 0, 0, 0 }


/* Geyser__SubscribeRequest__AccountsEntry methods */
void   geyser__subscribe_request__accounts_entry__init
                     (Geyser__SubscribeRequest__AccountsEntry         *message);
/* Geyser__SubscribeRequest__SlotsEntry methods */
void   geyser__subscribe_request__slots_entry__init
                     (Geyser__SubscribeRequest__SlotsEntry         *message);
/* Geyser__SubscribeRequest__TransactionsEntry methods */
void   geyser__subscribe_request__transactions_entry__init
                     (Geyser__SubscribeRequest__TransactionsEntry         *message);
/* Geyser__SubscribeRequest__TransactionsStatusEntry methods */
void   geyser__subscribe_request__transactions_status_entry__init
                     (Geyser__SubscribeRequest__TransactionsStatusEntry         *message);
/* Geyser__SubscribeRequest__BlocksEntry methods */
void   geyser__subscribe_request__blocks_entry__init
                     (Geyser__SubscribeRequest__BlocksEntry         *message);
/* Geyser__SubscribeRequest__BlocksMetaEntry methods */
void   geyser__subscribe_request__blocks_meta_entry__init
                     (Geyser__SubscribeRequest__BlocksMetaEntry         *message);
/* Geyser__SubscribeRequest__EntryEntry methods */
void   geyser__subscribe_request__entry_entry__init
                     (Geyser__SubscribeRequest__EntryEntry         *message);
/* Geyser__SubscribeRequest methods */
void   geyser__subscribe_request__init
                     (Geyser__SubscribeRequest         *message);
size_t geyser__subscribe_request__get_packed_size
                     (const Geyser__SubscribeRequest   *message);
size_t geyser__subscribe_request__pack
                     (const Geyser__SubscribeRequest   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request__pack_to_buffer
                     (const Geyser__SubscribeRequest   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequest *
       geyser__subscribe_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request__free_unpacked
                     (Geyser__SubscribeRequest *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestFilterAccounts methods */
void   geyser__subscribe_request_filter_accounts__init
                     (Geyser__SubscribeRequestFilterAccounts         *message);
size_t geyser__subscribe_request_filter_accounts__get_packed_size
                     (const Geyser__SubscribeRequestFilterAccounts   *message);
size_t geyser__subscribe_request_filter_accounts__pack
                     (const Geyser__SubscribeRequestFilterAccounts   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_filter_accounts__pack_to_buffer
                     (const Geyser__SubscribeRequestFilterAccounts   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestFilterAccounts *
       geyser__subscribe_request_filter_accounts__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_filter_accounts__free_unpacked
                     (Geyser__SubscribeRequestFilterAccounts *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestFilterAccountsFilter methods */
void   geyser__subscribe_request_filter_accounts_filter__init
                     (Geyser__SubscribeRequestFilterAccountsFilter         *message);
size_t geyser__subscribe_request_filter_accounts_filter__get_packed_size
                     (const Geyser__SubscribeRequestFilterAccountsFilter   *message);
size_t geyser__subscribe_request_filter_accounts_filter__pack
                     (const Geyser__SubscribeRequestFilterAccountsFilter   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_filter_accounts_filter__pack_to_buffer
                     (const Geyser__SubscribeRequestFilterAccountsFilter   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestFilterAccountsFilter *
       geyser__subscribe_request_filter_accounts_filter__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_filter_accounts_filter__free_unpacked
                     (Geyser__SubscribeRequestFilterAccountsFilter *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestFilterAccountsFilterMemcmp methods */
void   geyser__subscribe_request_filter_accounts_filter_memcmp__init
                     (Geyser__SubscribeRequestFilterAccountsFilterMemcmp         *message);
size_t geyser__subscribe_request_filter_accounts_filter_memcmp__get_packed_size
                     (const Geyser__SubscribeRequestFilterAccountsFilterMemcmp   *message);
size_t geyser__subscribe_request_filter_accounts_filter_memcmp__pack
                     (const Geyser__SubscribeRequestFilterAccountsFilterMemcmp   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_filter_accounts_filter_memcmp__pack_to_buffer
                     (const Geyser__SubscribeRequestFilterAccountsFilterMemcmp   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestFilterAccountsFilterMemcmp *
       geyser__subscribe_request_filter_accounts_filter_memcmp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_filter_accounts_filter_memcmp__free_unpacked
                     (Geyser__SubscribeRequestFilterAccountsFilterMemcmp *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestFilterAccountsFilterLamports methods */
void   geyser__subscribe_request_filter_accounts_filter_lamports__init
                     (Geyser__SubscribeRequestFilterAccountsFilterLamports         *message);
size_t geyser__subscribe_request_filter_accounts_filter_lamports__get_packed_size
                     (const Geyser__SubscribeRequestFilterAccountsFilterLamports   *message);
size_t geyser__subscribe_request_filter_accounts_filter_lamports__pack
                     (const Geyser__SubscribeRequestFilterAccountsFilterLamports   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_filter_accounts_filter_lamports__pack_to_buffer
                     (const Geyser__SubscribeRequestFilterAccountsFilterLamports   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestFilterAccountsFilterLamports *
       geyser__subscribe_request_filter_accounts_filter_lamports__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_filter_accounts_filter_lamports__free_unpacked
                     (Geyser__SubscribeRequestFilterAccountsFilterLamports *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestFilterSlots methods */
void   geyser__subscribe_request_filter_slots__init
                     (Geyser__SubscribeRequestFilterSlots         *message);
size_t geyser__subscribe_request_filter_slots__get_packed_size
                     (const Geyser__SubscribeRequestFilterSlots   *message);
size_t geyser__subscribe_request_filter_slots__pack
                     (const Geyser__SubscribeRequestFilterSlots   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_filter_slots__pack_to_buffer
                     (const Geyser__SubscribeRequestFilterSlots   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestFilterSlots *
       geyser__subscribe_request_filter_slots__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_filter_slots__free_unpacked
                     (Geyser__SubscribeRequestFilterSlots *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestFilterTransactions methods */
void   geyser__subscribe_request_filter_transactions__init
                     (Geyser__SubscribeRequestFilterTransactions         *message);
size_t geyser__subscribe_request_filter_transactions__get_packed_size
                     (const Geyser__SubscribeRequestFilterTransactions   *message);
size_t geyser__subscribe_request_filter_transactions__pack
                     (const Geyser__SubscribeRequestFilterTransactions   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_filter_transactions__pack_to_buffer
                     (const Geyser__SubscribeRequestFilterTransactions   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestFilterTransactions *
       geyser__subscribe_request_filter_transactions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_filter_transactions__free_unpacked
                     (Geyser__SubscribeRequestFilterTransactions *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestFilterBlocks methods */
void   geyser__subscribe_request_filter_blocks__init
                     (Geyser__SubscribeRequestFilterBlocks         *message);
size_t geyser__subscribe_request_filter_blocks__get_packed_size
                     (const Geyser__SubscribeRequestFilterBlocks   *message);
size_t geyser__subscribe_request_filter_blocks__pack
                     (const Geyser__SubscribeRequestFilterBlocks   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_filter_blocks__pack_to_buffer
                     (const Geyser__SubscribeRequestFilterBlocks   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestFilterBlocks *
       geyser__subscribe_request_filter_blocks__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_filter_blocks__free_unpacked
                     (Geyser__SubscribeRequestFilterBlocks *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestFilterBlocksMeta methods */
void   geyser__subscribe_request_filter_blocks_meta__init
                     (Geyser__SubscribeRequestFilterBlocksMeta         *message);
size_t geyser__subscribe_request_filter_blocks_meta__get_packed_size
                     (const Geyser__SubscribeRequestFilterBlocksMeta   *message);
size_t geyser__subscribe_request_filter_blocks_meta__pack
                     (const Geyser__SubscribeRequestFilterBlocksMeta   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_filter_blocks_meta__pack_to_buffer
                     (const Geyser__SubscribeRequestFilterBlocksMeta   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestFilterBlocksMeta *
       geyser__subscribe_request_filter_blocks_meta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_filter_blocks_meta__free_unpacked
                     (Geyser__SubscribeRequestFilterBlocksMeta *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestFilterEntry methods */
void   geyser__subscribe_request_filter_entry__init
                     (Geyser__SubscribeRequestFilterEntry         *message);
size_t geyser__subscribe_request_filter_entry__get_packed_size
                     (const Geyser__SubscribeRequestFilterEntry   *message);
size_t geyser__subscribe_request_filter_entry__pack
                     (const Geyser__SubscribeRequestFilterEntry   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_filter_entry__pack_to_buffer
                     (const Geyser__SubscribeRequestFilterEntry   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestFilterEntry *
       geyser__subscribe_request_filter_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_filter_entry__free_unpacked
                     (Geyser__SubscribeRequestFilterEntry *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestAccountsDataSlice methods */
void   geyser__subscribe_request_accounts_data_slice__init
                     (Geyser__SubscribeRequestAccountsDataSlice         *message);
size_t geyser__subscribe_request_accounts_data_slice__get_packed_size
                     (const Geyser__SubscribeRequestAccountsDataSlice   *message);
size_t geyser__subscribe_request_accounts_data_slice__pack
                     (const Geyser__SubscribeRequestAccountsDataSlice   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_accounts_data_slice__pack_to_buffer
                     (const Geyser__SubscribeRequestAccountsDataSlice   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestAccountsDataSlice *
       geyser__subscribe_request_accounts_data_slice__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_accounts_data_slice__free_unpacked
                     (Geyser__SubscribeRequestAccountsDataSlice *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeRequestPing methods */
void   geyser__subscribe_request_ping__init
                     (Geyser__SubscribeRequestPing         *message);
size_t geyser__subscribe_request_ping__get_packed_size
                     (const Geyser__SubscribeRequestPing   *message);
size_t geyser__subscribe_request_ping__pack
                     (const Geyser__SubscribeRequestPing   *message,
                      uint8_t             *out);
size_t geyser__subscribe_request_ping__pack_to_buffer
                     (const Geyser__SubscribeRequestPing   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeRequestPing *
       geyser__subscribe_request_ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_request_ping__free_unpacked
                     (Geyser__SubscribeRequestPing *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdate methods */
void   geyser__subscribe_update__init
                     (Geyser__SubscribeUpdate         *message);
size_t geyser__subscribe_update__get_packed_size
                     (const Geyser__SubscribeUpdate   *message);
size_t geyser__subscribe_update__pack
                     (const Geyser__SubscribeUpdate   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update__pack_to_buffer
                     (const Geyser__SubscribeUpdate   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdate *
       geyser__subscribe_update__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update__free_unpacked
                     (Geyser__SubscribeUpdate *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdateAccount methods */
void   geyser__subscribe_update_account__init
                     (Geyser__SubscribeUpdateAccount         *message);
size_t geyser__subscribe_update_account__get_packed_size
                     (const Geyser__SubscribeUpdateAccount   *message);
size_t geyser__subscribe_update_account__pack
                     (const Geyser__SubscribeUpdateAccount   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_account__pack_to_buffer
                     (const Geyser__SubscribeUpdateAccount   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdateAccount *
       geyser__subscribe_update_account__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_account__free_unpacked
                     (Geyser__SubscribeUpdateAccount *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdateAccountInfo methods */
void   geyser__subscribe_update_account_info__init
                     (Geyser__SubscribeUpdateAccountInfo         *message);
size_t geyser__subscribe_update_account_info__get_packed_size
                     (const Geyser__SubscribeUpdateAccountInfo   *message);
size_t geyser__subscribe_update_account_info__pack
                     (const Geyser__SubscribeUpdateAccountInfo   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_account_info__pack_to_buffer
                     (const Geyser__SubscribeUpdateAccountInfo   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdateAccountInfo *
       geyser__subscribe_update_account_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_account_info__free_unpacked
                     (Geyser__SubscribeUpdateAccountInfo *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdateSlot methods */
void   geyser__subscribe_update_slot__init
                     (Geyser__SubscribeUpdateSlot         *message);
size_t geyser__subscribe_update_slot__get_packed_size
                     (const Geyser__SubscribeUpdateSlot   *message);
size_t geyser__subscribe_update_slot__pack
                     (const Geyser__SubscribeUpdateSlot   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_slot__pack_to_buffer
                     (const Geyser__SubscribeUpdateSlot   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdateSlot *
       geyser__subscribe_update_slot__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_slot__free_unpacked
                     (Geyser__SubscribeUpdateSlot *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdateTransaction methods */
void   geyser__subscribe_update_transaction__init
                     (Geyser__SubscribeUpdateTransaction         *message);
size_t geyser__subscribe_update_transaction__get_packed_size
                     (const Geyser__SubscribeUpdateTransaction   *message);
size_t geyser__subscribe_update_transaction__pack
                     (const Geyser__SubscribeUpdateTransaction   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_transaction__pack_to_buffer
                     (const Geyser__SubscribeUpdateTransaction   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdateTransaction *
       geyser__subscribe_update_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_transaction__free_unpacked
                     (Geyser__SubscribeUpdateTransaction *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdateTransactionInfo methods */
void   geyser__subscribe_update_transaction_info__init
                     (Geyser__SubscribeUpdateTransactionInfo         *message);
size_t geyser__subscribe_update_transaction_info__get_packed_size
                     (const Geyser__SubscribeUpdateTransactionInfo   *message);
size_t geyser__subscribe_update_transaction_info__pack
                     (const Geyser__SubscribeUpdateTransactionInfo   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_transaction_info__pack_to_buffer
                     (const Geyser__SubscribeUpdateTransactionInfo   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdateTransactionInfo *
       geyser__subscribe_update_transaction_info__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_transaction_info__free_unpacked
                     (Geyser__SubscribeUpdateTransactionInfo *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdateTransactionStatus methods */
void   geyser__subscribe_update_transaction_status__init
                     (Geyser__SubscribeUpdateTransactionStatus         *message);
size_t geyser__subscribe_update_transaction_status__get_packed_size
                     (const Geyser__SubscribeUpdateTransactionStatus   *message);
size_t geyser__subscribe_update_transaction_status__pack
                     (const Geyser__SubscribeUpdateTransactionStatus   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_transaction_status__pack_to_buffer
                     (const Geyser__SubscribeUpdateTransactionStatus   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdateTransactionStatus *
       geyser__subscribe_update_transaction_status__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_transaction_status__free_unpacked
                     (Geyser__SubscribeUpdateTransactionStatus *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdateBlock methods */
void   geyser__subscribe_update_block__init
                     (Geyser__SubscribeUpdateBlock         *message);
size_t geyser__subscribe_update_block__get_packed_size
                     (const Geyser__SubscribeUpdateBlock   *message);
size_t geyser__subscribe_update_block__pack
                     (const Geyser__SubscribeUpdateBlock   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_block__pack_to_buffer
                     (const Geyser__SubscribeUpdateBlock   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdateBlock *
       geyser__subscribe_update_block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_block__free_unpacked
                     (Geyser__SubscribeUpdateBlock *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdateBlockMeta methods */
void   geyser__subscribe_update_block_meta__init
                     (Geyser__SubscribeUpdateBlockMeta         *message);
size_t geyser__subscribe_update_block_meta__get_packed_size
                     (const Geyser__SubscribeUpdateBlockMeta   *message);
size_t geyser__subscribe_update_block_meta__pack
                     (const Geyser__SubscribeUpdateBlockMeta   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_block_meta__pack_to_buffer
                     (const Geyser__SubscribeUpdateBlockMeta   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdateBlockMeta *
       geyser__subscribe_update_block_meta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_block_meta__free_unpacked
                     (Geyser__SubscribeUpdateBlockMeta *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdateEntry methods */
void   geyser__subscribe_update_entry__init
                     (Geyser__SubscribeUpdateEntry         *message);
size_t geyser__subscribe_update_entry__get_packed_size
                     (const Geyser__SubscribeUpdateEntry   *message);
size_t geyser__subscribe_update_entry__pack
                     (const Geyser__SubscribeUpdateEntry   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_entry__pack_to_buffer
                     (const Geyser__SubscribeUpdateEntry   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdateEntry *
       geyser__subscribe_update_entry__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_entry__free_unpacked
                     (Geyser__SubscribeUpdateEntry *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdatePing methods */
void   geyser__subscribe_update_ping__init
                     (Geyser__SubscribeUpdatePing         *message);
size_t geyser__subscribe_update_ping__get_packed_size
                     (const Geyser__SubscribeUpdatePing   *message);
size_t geyser__subscribe_update_ping__pack
                     (const Geyser__SubscribeUpdatePing   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_ping__pack_to_buffer
                     (const Geyser__SubscribeUpdatePing   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdatePing *
       geyser__subscribe_update_ping__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_ping__free_unpacked
                     (Geyser__SubscribeUpdatePing *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeUpdatePong methods */
void   geyser__subscribe_update_pong__init
                     (Geyser__SubscribeUpdatePong         *message);
size_t geyser__subscribe_update_pong__get_packed_size
                     (const Geyser__SubscribeUpdatePong   *message);
size_t geyser__subscribe_update_pong__pack
                     (const Geyser__SubscribeUpdatePong   *message,
                      uint8_t             *out);
size_t geyser__subscribe_update_pong__pack_to_buffer
                     (const Geyser__SubscribeUpdatePong   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeUpdatePong *
       geyser__subscribe_update_pong__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_update_pong__free_unpacked
                     (Geyser__SubscribeUpdatePong *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeReplayInfoRequest methods */
void   geyser__subscribe_replay_info_request__init
                     (Geyser__SubscribeReplayInfoRequest         *message);
size_t geyser__subscribe_replay_info_request__get_packed_size
                     (const Geyser__SubscribeReplayInfoRequest   *message);
size_t geyser__subscribe_replay_info_request__pack
                     (const Geyser__SubscribeReplayInfoRequest   *message,
                      uint8_t             *out);
size_t geyser__subscribe_replay_info_request__pack_to_buffer
                     (const Geyser__SubscribeReplayInfoRequest   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeReplayInfoRequest *
       geyser__subscribe_replay_info_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_replay_info_request__free_unpacked
                     (Geyser__SubscribeReplayInfoRequest *message,
                      ProtobufCAllocator *allocator);
/* Geyser__SubscribeReplayInfoResponse methods */
void   geyser__subscribe_replay_info_response__init
                     (Geyser__SubscribeReplayInfoResponse         *message);
size_t geyser__subscribe_replay_info_response__get_packed_size
                     (const Geyser__SubscribeReplayInfoResponse   *message);
size_t geyser__subscribe_replay_info_response__pack
                     (const Geyser__SubscribeReplayInfoResponse   *message,
                      uint8_t             *out);
size_t geyser__subscribe_replay_info_response__pack_to_buffer
                     (const Geyser__SubscribeReplayInfoResponse   *message,
                      ProtobufCBuffer     *buffer);
Geyser__SubscribeReplayInfoResponse *
       geyser__subscribe_replay_info_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__subscribe_replay_info_response__free_unpacked
                     (Geyser__SubscribeReplayInfoResponse *message,
                      ProtobufCAllocator *allocator);
/* Geyser__PingRequest methods */
void   geyser__ping_request__init
                     (Geyser__PingRequest         *message);
size_t geyser__ping_request__get_packed_size
                     (const Geyser__PingRequest   *message);
size_t geyser__ping_request__pack
                     (const Geyser__PingRequest   *message,
                      uint8_t             *out);
size_t geyser__ping_request__pack_to_buffer
                     (const Geyser__PingRequest   *message,
                      ProtobufCBuffer     *buffer);
Geyser__PingRequest *
       geyser__ping_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__ping_request__free_unpacked
                     (Geyser__PingRequest *message,
                      ProtobufCAllocator *allocator);
/* Geyser__PongResponse methods */
void   geyser__pong_response__init
                     (Geyser__PongResponse         *message);
size_t geyser__pong_response__get_packed_size
                     (const Geyser__PongResponse   *message);
size_t geyser__pong_response__pack
                     (const Geyser__PongResponse   *message,
                      uint8_t             *out);
size_t geyser__pong_response__pack_to_buffer
                     (const Geyser__PongResponse   *message,
                      ProtobufCBuffer     *buffer);
Geyser__PongResponse *
       geyser__pong_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__pong_response__free_unpacked
                     (Geyser__PongResponse *message,
                      ProtobufCAllocator *allocator);
/* Geyser__GetLatestBlockhashRequest methods */
void   geyser__get_latest_blockhash_request__init
                     (Geyser__GetLatestBlockhashRequest         *message);
size_t geyser__get_latest_blockhash_request__get_packed_size
                     (const Geyser__GetLatestBlockhashRequest   *message);
size_t geyser__get_latest_blockhash_request__pack
                     (const Geyser__GetLatestBlockhashRequest   *message,
                      uint8_t             *out);
size_t geyser__get_latest_blockhash_request__pack_to_buffer
                     (const Geyser__GetLatestBlockhashRequest   *message,
                      ProtobufCBuffer     *buffer);
Geyser__GetLatestBlockhashRequest *
       geyser__get_latest_blockhash_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__get_latest_blockhash_request__free_unpacked
                     (Geyser__GetLatestBlockhashRequest *message,
                      ProtobufCAllocator *allocator);
/* Geyser__GetLatestBlockhashResponse methods */
void   geyser__get_latest_blockhash_response__init
                     (Geyser__GetLatestBlockhashResponse         *message);
size_t geyser__get_latest_blockhash_response__get_packed_size
                     (const Geyser__GetLatestBlockhashResponse   *message);
size_t geyser__get_latest_blockhash_response__pack
                     (const Geyser__GetLatestBlockhashResponse   *message,
                      uint8_t             *out);
size_t geyser__get_latest_blockhash_response__pack_to_buffer
                     (const Geyser__GetLatestBlockhashResponse   *message,
                      ProtobufCBuffer     *buffer);
Geyser__GetLatestBlockhashResponse *
       geyser__get_latest_blockhash_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__get_latest_blockhash_response__free_unpacked
                     (Geyser__GetLatestBlockhashResponse *message,
                      ProtobufCAllocator *allocator);
/* Geyser__GetBlockHeightRequest methods */
void   geyser__get_block_height_request__init
                     (Geyser__GetBlockHeightRequest         *message);
size_t geyser__get_block_height_request__get_packed_size
                     (const Geyser__GetBlockHeightRequest   *message);
size_t geyser__get_block_height_request__pack
                     (const Geyser__GetBlockHeightRequest   *message,
                      uint8_t             *out);
size_t geyser__get_block_height_request__pack_to_buffer
                     (const Geyser__GetBlockHeightRequest   *message,
                      ProtobufCBuffer     *buffer);
Geyser__GetBlockHeightRequest *
       geyser__get_block_height_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__get_block_height_request__free_unpacked
                     (Geyser__GetBlockHeightRequest *message,
                      ProtobufCAllocator *allocator);
/* Geyser__GetBlockHeightResponse methods */
void   geyser__get_block_height_response__init
                     (Geyser__GetBlockHeightResponse         *message);
size_t geyser__get_block_height_response__get_packed_size
                     (const Geyser__GetBlockHeightResponse   *message);
size_t geyser__get_block_height_response__pack
                     (const Geyser__GetBlockHeightResponse   *message,
                      uint8_t             *out);
size_t geyser__get_block_height_response__pack_to_buffer
                     (const Geyser__GetBlockHeightResponse   *message,
                      ProtobufCBuffer     *buffer);
Geyser__GetBlockHeightResponse *
       geyser__get_block_height_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__get_block_height_response__free_unpacked
                     (Geyser__GetBlockHeightResponse *message,
                      ProtobufCAllocator *allocator);
/* Geyser__GetSlotRequest methods */
void   geyser__get_slot_request__init
                     (Geyser__GetSlotRequest         *message);
size_t geyser__get_slot_request__get_packed_size
                     (const Geyser__GetSlotRequest   *message);
size_t geyser__get_slot_request__pack
                     (const Geyser__GetSlotRequest   *message,
                      uint8_t             *out);
size_t geyser__get_slot_request__pack_to_buffer
                     (const Geyser__GetSlotRequest   *message,
                      ProtobufCBuffer     *buffer);
Geyser__GetSlotRequest *
       geyser__get_slot_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__get_slot_request__free_unpacked
                     (Geyser__GetSlotRequest *message,
                      ProtobufCAllocator *allocator);
/* Geyser__GetSlotResponse methods */
void   geyser__get_slot_response__init
                     (Geyser__GetSlotResponse         *message);
size_t geyser__get_slot_response__get_packed_size
                     (const Geyser__GetSlotResponse   *message);
size_t geyser__get_slot_response__pack
                     (const Geyser__GetSlotResponse   *message,
                      uint8_t             *out);
size_t geyser__get_slot_response__pack_to_buffer
                     (const Geyser__GetSlotResponse   *message,
                      ProtobufCBuffer     *buffer);
Geyser__GetSlotResponse *
       geyser__get_slot_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__get_slot_response__free_unpacked
                     (Geyser__GetSlotResponse *message,
                      ProtobufCAllocator *allocator);
/* Geyser__GetVersionRequest methods */
void   geyser__get_version_request__init
                     (Geyser__GetVersionRequest         *message);
size_t geyser__get_version_request__get_packed_size
                     (const Geyser__GetVersionRequest   *message);
size_t geyser__get_version_request__pack
                     (const Geyser__GetVersionRequest   *message,
                      uint8_t             *out);
size_t geyser__get_version_request__pack_to_buffer
                     (const Geyser__GetVersionRequest   *message,
                      ProtobufCBuffer     *buffer);
Geyser__GetVersionRequest *
       geyser__get_version_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__get_version_request__free_unpacked
                     (Geyser__GetVersionRequest *message,
                      ProtobufCAllocator *allocator);
/* Geyser__GetVersionResponse methods */
void   geyser__get_version_response__init
                     (Geyser__GetVersionResponse         *message);
size_t geyser__get_version_response__get_packed_size
                     (const Geyser__GetVersionResponse   *message);
size_t geyser__get_version_response__pack
                     (const Geyser__GetVersionResponse   *message,
                      uint8_t             *out);
size_t geyser__get_version_response__pack_to_buffer
                     (const Geyser__GetVersionResponse   *message,
                      ProtobufCBuffer     *buffer);
Geyser__GetVersionResponse *
       geyser__get_version_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__get_version_response__free_unpacked
                     (Geyser__GetVersionResponse *message,
                      ProtobufCAllocator *allocator);
/* Geyser__IsBlockhashValidRequest methods */
void   geyser__is_blockhash_valid_request__init
                     (Geyser__IsBlockhashValidRequest         *message);
size_t geyser__is_blockhash_valid_request__get_packed_size
                     (const Geyser__IsBlockhashValidRequest   *message);
size_t geyser__is_blockhash_valid_request__pack
                     (const Geyser__IsBlockhashValidRequest   *message,
                      uint8_t             *out);
size_t geyser__is_blockhash_valid_request__pack_to_buffer
                     (const Geyser__IsBlockhashValidRequest   *message,
                      ProtobufCBuffer     *buffer);
Geyser__IsBlockhashValidRequest *
       geyser__is_blockhash_valid_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__is_blockhash_valid_request__free_unpacked
                     (Geyser__IsBlockhashValidRequest *message,
                      ProtobufCAllocator *allocator);
/* Geyser__IsBlockhashValidResponse methods */
void   geyser__is_blockhash_valid_response__init
                     (Geyser__IsBlockhashValidResponse         *message);
size_t geyser__is_blockhash_valid_response__get_packed_size
                     (const Geyser__IsBlockhashValidResponse   *message);
size_t geyser__is_blockhash_valid_response__pack
                     (const Geyser__IsBlockhashValidResponse   *message,
                      uint8_t             *out);
size_t geyser__is_blockhash_valid_response__pack_to_buffer
                     (const Geyser__IsBlockhashValidResponse   *message,
                      ProtobufCBuffer     *buffer);
Geyser__IsBlockhashValidResponse *
       geyser__is_blockhash_valid_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   geyser__is_blockhash_valid_response__free_unpacked
                     (Geyser__IsBlockhashValidResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Geyser__SubscribeRequest__AccountsEntry_Closure)
                 (const Geyser__SubscribeRequest__AccountsEntry *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequest__SlotsEntry_Closure)
                 (const Geyser__SubscribeRequest__SlotsEntry *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequest__TransactionsEntry_Closure)
                 (const Geyser__SubscribeRequest__TransactionsEntry *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequest__TransactionsStatusEntry_Closure)
                 (const Geyser__SubscribeRequest__TransactionsStatusEntry *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequest__BlocksEntry_Closure)
                 (const Geyser__SubscribeRequest__BlocksEntry *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequest__BlocksMetaEntry_Closure)
                 (const Geyser__SubscribeRequest__BlocksMetaEntry *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequest__EntryEntry_Closure)
                 (const Geyser__SubscribeRequest__EntryEntry *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequest_Closure)
                 (const Geyser__SubscribeRequest *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestFilterAccounts_Closure)
                 (const Geyser__SubscribeRequestFilterAccounts *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestFilterAccountsFilter_Closure)
                 (const Geyser__SubscribeRequestFilterAccountsFilter *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestFilterAccountsFilterMemcmp_Closure)
                 (const Geyser__SubscribeRequestFilterAccountsFilterMemcmp *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestFilterAccountsFilterLamports_Closure)
                 (const Geyser__SubscribeRequestFilterAccountsFilterLamports *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestFilterSlots_Closure)
                 (const Geyser__SubscribeRequestFilterSlots *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestFilterTransactions_Closure)
                 (const Geyser__SubscribeRequestFilterTransactions *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestFilterBlocks_Closure)
                 (const Geyser__SubscribeRequestFilterBlocks *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestFilterBlocksMeta_Closure)
                 (const Geyser__SubscribeRequestFilterBlocksMeta *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestFilterEntry_Closure)
                 (const Geyser__SubscribeRequestFilterEntry *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestAccountsDataSlice_Closure)
                 (const Geyser__SubscribeRequestAccountsDataSlice *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeRequestPing_Closure)
                 (const Geyser__SubscribeRequestPing *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdate_Closure)
                 (const Geyser__SubscribeUpdate *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdateAccount_Closure)
                 (const Geyser__SubscribeUpdateAccount *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdateAccountInfo_Closure)
                 (const Geyser__SubscribeUpdateAccountInfo *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdateSlot_Closure)
                 (const Geyser__SubscribeUpdateSlot *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdateTransaction_Closure)
                 (const Geyser__SubscribeUpdateTransaction *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdateTransactionInfo_Closure)
                 (const Geyser__SubscribeUpdateTransactionInfo *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdateTransactionStatus_Closure)
                 (const Geyser__SubscribeUpdateTransactionStatus *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdateBlock_Closure)
                 (const Geyser__SubscribeUpdateBlock *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdateBlockMeta_Closure)
                 (const Geyser__SubscribeUpdateBlockMeta *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdateEntry_Closure)
                 (const Geyser__SubscribeUpdateEntry *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdatePing_Closure)
                 (const Geyser__SubscribeUpdatePing *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeUpdatePong_Closure)
                 (const Geyser__SubscribeUpdatePong *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeReplayInfoRequest_Closure)
                 (const Geyser__SubscribeReplayInfoRequest *message,
                  void *closure_data);
typedef void (*Geyser__SubscribeReplayInfoResponse_Closure)
                 (const Geyser__SubscribeReplayInfoResponse *message,
                  void *closure_data);
typedef void (*Geyser__PingRequest_Closure)
                 (const Geyser__PingRequest *message,
                  void *closure_data);
typedef void (*Geyser__PongResponse_Closure)
                 (const Geyser__PongResponse *message,
                  void *closure_data);
typedef void (*Geyser__GetLatestBlockhashRequest_Closure)
                 (const Geyser__GetLatestBlockhashRequest *message,
                  void *closure_data);
typedef void (*Geyser__GetLatestBlockhashResponse_Closure)
                 (const Geyser__GetLatestBlockhashResponse *message,
                  void *closure_data);
typedef void (*Geyser__GetBlockHeightRequest_Closure)
                 (const Geyser__GetBlockHeightRequest *message,
                  void *closure_data);
typedef void (*Geyser__GetBlockHeightResponse_Closure)
                 (const Geyser__GetBlockHeightResponse *message,
                  void *closure_data);
typedef void (*Geyser__GetSlotRequest_Closure)
                 (const Geyser__GetSlotRequest *message,
                  void *closure_data);
typedef void (*Geyser__GetSlotResponse_Closure)
                 (const Geyser__GetSlotResponse *message,
                  void *closure_data);
typedef void (*Geyser__GetVersionRequest_Closure)
                 (const Geyser__GetVersionRequest *message,
                  void *closure_data);
typedef void (*Geyser__GetVersionResponse_Closure)
                 (const Geyser__GetVersionResponse *message,
                  void *closure_data);
typedef void (*Geyser__IsBlockhashValidRequest_Closure)
                 (const Geyser__IsBlockhashValidRequest *message,
                  void *closure_data);
typedef void (*Geyser__IsBlockhashValidResponse_Closure)
                 (const Geyser__IsBlockhashValidResponse *message,
                  void *closure_data);

/* --- services --- */

typedef struct Geyser__Geyser_Service Geyser__Geyser_Service;
struct Geyser__Geyser_Service
{
  ProtobufCService base;
  void (*subscribe)(Geyser__Geyser_Service *service,
                    const Geyser__SubscribeRequest *input,
                    Geyser__SubscribeUpdate_Closure closure,
                    void *closure_data);
  void (*subscribe_replay_info)(Geyser__Geyser_Service *service,
                                const Geyser__SubscribeReplayInfoRequest *input,
                                Geyser__SubscribeReplayInfoResponse_Closure closure,
                                void *closure_data);
  void (*ping)(Geyser__Geyser_Service *service,
               const Geyser__PingRequest *input,
               Geyser__PongResponse_Closure closure,
               void *closure_data);
  void (*get_latest_blockhash)(Geyser__Geyser_Service *service,
                               const Geyser__GetLatestBlockhashRequest *input,
                               Geyser__GetLatestBlockhashResponse_Closure closure,
                               void *closure_data);
  void (*get_block_height)(Geyser__Geyser_Service *service,
                           const Geyser__GetBlockHeightRequest *input,
                           Geyser__GetBlockHeightResponse_Closure closure,
                           void *closure_data);
  void (*get_slot)(Geyser__Geyser_Service *service,
                   const Geyser__GetSlotRequest *input,
                   Geyser__GetSlotResponse_Closure closure,
                   void *closure_data);
  void (*is_blockhash_valid)(Geyser__Geyser_Service *service,
                             const Geyser__IsBlockhashValidRequest *input,
                             Geyser__IsBlockhashValidResponse_Closure closure,
                             void *closure_data);
  void (*get_version)(Geyser__Geyser_Service *service,
                      const Geyser__GetVersionRequest *input,
                      Geyser__GetVersionResponse_Closure closure,
                      void *closure_data);
};
typedef void (*Geyser__Geyser_ServiceDestroy)(Geyser__Geyser_Service *);
void geyser__geyser__init (Geyser__Geyser_Service *service,
                           Geyser__Geyser_ServiceDestroy destroy);
#define GEYSER__GEYSER__BASE_INIT \
    { &geyser__geyser__descriptor, protobuf_c_service_invoke_internal, NULL }
#define GEYSER__GEYSER__INIT(function_prefix__) \
    { GEYSER__GEYSER__BASE_INIT,\
      function_prefix__ ## subscribe,\
      function_prefix__ ## subscribe_replay_info,\
      function_prefix__ ## ping,\
      function_prefix__ ## get_latest_blockhash,\
      function_prefix__ ## get_block_height,\
      function_prefix__ ## get_slot,\
      function_prefix__ ## is_blockhash_valid,\
      function_prefix__ ## get_version  }
void geyser__geyser__subscribe(ProtobufCService *service,
                               const Geyser__SubscribeRequest *input,
                               Geyser__SubscribeUpdate_Closure closure,
                               void *closure_data);
void geyser__geyser__subscribe_replay_info(ProtobufCService *service,
                                           const Geyser__SubscribeReplayInfoRequest *input,
                                           Geyser__SubscribeReplayInfoResponse_Closure closure,
                                           void *closure_data);
void geyser__geyser__ping(ProtobufCService *service,
                          const Geyser__PingRequest *input,
                          Geyser__PongResponse_Closure closure,
                          void *closure_data);
void geyser__geyser__get_latest_blockhash(ProtobufCService *service,
                                          const Geyser__GetLatestBlockhashRequest *input,
                                          Geyser__GetLatestBlockhashResponse_Closure closure,
                                          void *closure_data);
void geyser__geyser__get_block_height(ProtobufCService *service,
                                      const Geyser__GetBlockHeightRequest *input,
                                      Geyser__GetBlockHeightResponse_Closure closure,
                                      void *closure_data);
void geyser__geyser__get_slot(ProtobufCService *service,
                              const Geyser__GetSlotRequest *input,
                              Geyser__GetSlotResponse_Closure closure,
                              void *closure_data);
void geyser__geyser__is_blockhash_valid(ProtobufCService *service,
                                        const Geyser__IsBlockhashValidRequest *input,
                                        Geyser__IsBlockhashValidResponse_Closure closure,
                                        void *closure_data);
void geyser__geyser__get_version(ProtobufCService *service,
                                 const Geyser__GetVersionRequest *input,
                                 Geyser__GetVersionResponse_Closure closure,
                                 void *closure_data);

/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    geyser__commitment_level__descriptor;
extern const ProtobufCEnumDescriptor    geyser__slot_status__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request__accounts_entry__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request__slots_entry__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request__transactions_entry__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request__transactions_status_entry__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request__blocks_entry__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request__blocks_meta_entry__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request__entry_entry__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_filter_accounts__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_filter_accounts_filter__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_filter_accounts_filter_memcmp__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_filter_accounts_filter_lamports__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_filter_slots__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_filter_transactions__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_filter_blocks__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_filter_blocks_meta__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_filter_entry__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_accounts_data_slice__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_request_ping__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_account__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_account_info__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_slot__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_transaction__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_transaction_info__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_transaction_status__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_block__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_block_meta__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_entry__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_ping__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_update_pong__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_replay_info_request__descriptor;
extern const ProtobufCMessageDescriptor geyser__subscribe_replay_info_response__descriptor;
extern const ProtobufCMessageDescriptor geyser__ping_request__descriptor;
extern const ProtobufCMessageDescriptor geyser__pong_response__descriptor;
extern const ProtobufCMessageDescriptor geyser__get_latest_blockhash_request__descriptor;
extern const ProtobufCMessageDescriptor geyser__get_latest_blockhash_response__descriptor;
extern const ProtobufCMessageDescriptor geyser__get_block_height_request__descriptor;
extern const ProtobufCMessageDescriptor geyser__get_block_height_response__descriptor;
extern const ProtobufCMessageDescriptor geyser__get_slot_request__descriptor;
extern const ProtobufCMessageDescriptor geyser__get_slot_response__descriptor;
extern const ProtobufCMessageDescriptor geyser__get_version_request__descriptor;
extern const ProtobufCMessageDescriptor geyser__get_version_response__descriptor;
extern const ProtobufCMessageDescriptor geyser__is_blockhash_valid_request__descriptor;
extern const ProtobufCMessageDescriptor geyser__is_blockhash_valid_response__descriptor;
extern const ProtobufCServiceDescriptor geyser__geyser__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_geyser_2eproto__INCLUDED */
