/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: solana-storage.proto */

#ifndef PROTOBUF_C_solana_2dstorage_2eproto__INCLUDED
#define PROTOBUF_C_solana_2dstorage_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005000 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct Solana__Storage__ConfirmedBlock__ConfirmedBlock Solana__Storage__ConfirmedBlock__ConfirmedBlock;
typedef struct Solana__Storage__ConfirmedBlock__ConfirmedTransaction Solana__Storage__ConfirmedBlock__ConfirmedTransaction;
typedef struct Solana__Storage__ConfirmedBlock__Transaction Solana__Storage__ConfirmedBlock__Transaction;
typedef struct Solana__Storage__ConfirmedBlock__Message Solana__Storage__ConfirmedBlock__Message;
typedef struct Solana__Storage__ConfirmedBlock__MessageHeader Solana__Storage__ConfirmedBlock__MessageHeader;
typedef struct Solana__Storage__ConfirmedBlock__MessageAddressTableLookup Solana__Storage__ConfirmedBlock__MessageAddressTableLookup;
typedef struct Solana__Storage__ConfirmedBlock__TransactionStatusMeta Solana__Storage__ConfirmedBlock__TransactionStatusMeta;
typedef struct Solana__Storage__ConfirmedBlock__TransactionError Solana__Storage__ConfirmedBlock__TransactionError;
typedef struct Solana__Storage__ConfirmedBlock__InnerInstructions Solana__Storage__ConfirmedBlock__InnerInstructions;
typedef struct Solana__Storage__ConfirmedBlock__InnerInstruction Solana__Storage__ConfirmedBlock__InnerInstruction;
typedef struct Solana__Storage__ConfirmedBlock__CompiledInstruction Solana__Storage__ConfirmedBlock__CompiledInstruction;
typedef struct Solana__Storage__ConfirmedBlock__TokenBalance Solana__Storage__ConfirmedBlock__TokenBalance;
typedef struct Solana__Storage__ConfirmedBlock__UiTokenAmount Solana__Storage__ConfirmedBlock__UiTokenAmount;
typedef struct Solana__Storage__ConfirmedBlock__ReturnData Solana__Storage__ConfirmedBlock__ReturnData;
typedef struct Solana__Storage__ConfirmedBlock__Reward Solana__Storage__ConfirmedBlock__Reward;
typedef struct Solana__Storage__ConfirmedBlock__Rewards Solana__Storage__ConfirmedBlock__Rewards;
typedef struct Solana__Storage__ConfirmedBlock__UnixTimestamp Solana__Storage__ConfirmedBlock__UnixTimestamp;
typedef struct Solana__Storage__ConfirmedBlock__BlockHeight Solana__Storage__ConfirmedBlock__BlockHeight;
typedef struct Solana__Storage__ConfirmedBlock__NumPartitions Solana__Storage__ConfirmedBlock__NumPartitions;


/* --- enums --- */

typedef enum _Solana__Storage__ConfirmedBlock__RewardType {
  SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Unspecified = 0,
  SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Fee = 1,
  SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Rent = 2,
  SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Staking = 3,
  SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Voting = 4
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE)
} Solana__Storage__ConfirmedBlock__RewardType;

/* --- messages --- */

struct  Solana__Storage__ConfirmedBlock__ConfirmedBlock
{
  ProtobufCMessage base;
  char *previous_blockhash;
  char *blockhash;
  protobuf_c_boolean has_parent_slot;
  uint64_t parent_slot;
  size_t n_transactions;
  Solana__Storage__ConfirmedBlock__ConfirmedTransaction **transactions;
  size_t n_rewards;
  Solana__Storage__ConfirmedBlock__Reward **rewards;
  Solana__Storage__ConfirmedBlock__UnixTimestamp *block_time;
  Solana__Storage__ConfirmedBlock__BlockHeight *block_height;
  Solana__Storage__ConfirmedBlock__NumPartitions *num_partitions;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__CONFIRMED_BLOCK__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__confirmed_block__descriptor) \
    , NULL, NULL, 0, 0, 0,NULL, 0,NULL, NULL, NULL, NULL }


struct  Solana__Storage__ConfirmedBlock__ConfirmedTransaction
{
  ProtobufCMessage base;
  Solana__Storage__ConfirmedBlock__Transaction *transaction;
  Solana__Storage__ConfirmedBlock__TransactionStatusMeta *meta;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__CONFIRMED_TRANSACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__confirmed_transaction__descriptor) \
    , NULL, NULL }


struct  Solana__Storage__ConfirmedBlock__Transaction
{
  ProtobufCMessage base;
  size_t n_signatures;
  ProtobufCBinaryData *signatures;
  Solana__Storage__ConfirmedBlock__Message *message;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__TRANSACTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__transaction__descriptor) \
    , 0,NULL, NULL }


struct  Solana__Storage__ConfirmedBlock__Message
{
  ProtobufCMessage base;
  Solana__Storage__ConfirmedBlock__MessageHeader *header;
  size_t n_account_keys;
  ProtobufCBinaryData *account_keys;
  protobuf_c_boolean has_recent_blockhash;
  ProtobufCBinaryData recent_blockhash;
  size_t n_instructions;
  Solana__Storage__ConfirmedBlock__CompiledInstruction **instructions;
  protobuf_c_boolean has_versioned;
  protobuf_c_boolean versioned;
  size_t n_address_table_lookups;
  Solana__Storage__ConfirmedBlock__MessageAddressTableLookup **address_table_lookups;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__message__descriptor) \
    , NULL, 0,NULL, 0, {0,NULL}, 0,NULL, 0, 0, 0,NULL }


struct  Solana__Storage__ConfirmedBlock__MessageHeader
{
  ProtobufCMessage base;
  protobuf_c_boolean has_num_required_signatures;
  uint32_t num_required_signatures;
  protobuf_c_boolean has_num_readonly_signed_accounts;
  uint32_t num_readonly_signed_accounts;
  protobuf_c_boolean has_num_readonly_unsigned_accounts;
  uint32_t num_readonly_unsigned_accounts;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__MESSAGE_HEADER__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__message_header__descriptor) \
    , 0, 0, 0, 0, 0, 0 }


struct  Solana__Storage__ConfirmedBlock__MessageAddressTableLookup
{
  ProtobufCMessage base;
  protobuf_c_boolean has_account_key;
  ProtobufCBinaryData account_key;
  protobuf_c_boolean has_writable_indexes;
  ProtobufCBinaryData writable_indexes;
  protobuf_c_boolean has_readonly_indexes;
  ProtobufCBinaryData readonly_indexes;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__MESSAGE_ADDRESS_TABLE_LOOKUP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__message_address_table_lookup__descriptor) \
    , 0, {0,NULL}, 0, {0,NULL}, 0, {0,NULL} }


struct  Solana__Storage__ConfirmedBlock__TransactionStatusMeta
{
  ProtobufCMessage base;
  Solana__Storage__ConfirmedBlock__TransactionError *err;
  protobuf_c_boolean has_fee;
  uint64_t fee;
  size_t n_pre_balances;
  uint64_t *pre_balances;
  size_t n_post_balances;
  uint64_t *post_balances;
  size_t n_inner_instructions;
  Solana__Storage__ConfirmedBlock__InnerInstructions **inner_instructions;
  protobuf_c_boolean has_inner_instructions_none;
  protobuf_c_boolean inner_instructions_none;
  size_t n_log_messages;
  char **log_messages;
  protobuf_c_boolean has_log_messages_none;
  protobuf_c_boolean log_messages_none;
  size_t n_pre_token_balances;
  Solana__Storage__ConfirmedBlock__TokenBalance **pre_token_balances;
  size_t n_post_token_balances;
  Solana__Storage__ConfirmedBlock__TokenBalance **post_token_balances;
  size_t n_rewards;
  Solana__Storage__ConfirmedBlock__Reward **rewards;
  size_t n_loaded_writable_addresses;
  ProtobufCBinaryData *loaded_writable_addresses;
  size_t n_loaded_readonly_addresses;
  ProtobufCBinaryData *loaded_readonly_addresses;
  Solana__Storage__ConfirmedBlock__ReturnData *return_data;
  protobuf_c_boolean has_return_data_none;
  protobuf_c_boolean return_data_none;
  /*
   * Sum of compute units consumed by all instructions.
   * Available since Solana v1.10.35 / v1.11.6.
   * Set to `None` for txs executed on earlier versions.
   */
  protobuf_c_boolean has_compute_units_consumed;
  uint64_t compute_units_consumed;
  /*
   * Total transaction cost
   */
  protobuf_c_boolean has_cost_units;
  uint64_t cost_units;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__TRANSACTION_STATUS_META__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__transaction_status_meta__descriptor) \
    , NULL, 0, 0, 0,NULL, 0,NULL, 0,NULL, 0, 0, 0,NULL, 0, 0, 0,NULL, 0,NULL, 0,NULL, 0,NULL, 0,NULL, NULL, 0, 0, 0, 0, 0, 0 }


struct  Solana__Storage__ConfirmedBlock__TransactionError
{
  ProtobufCMessage base;
  protobuf_c_boolean has_err;
  ProtobufCBinaryData err;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__TRANSACTION_ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__transaction_error__descriptor) \
    , 0, {0,NULL} }


struct  Solana__Storage__ConfirmedBlock__InnerInstructions
{
  ProtobufCMessage base;
  protobuf_c_boolean has_index;
  uint32_t index;
  size_t n_instructions;
  Solana__Storage__ConfirmedBlock__InnerInstruction **instructions;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__INNER_INSTRUCTIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__inner_instructions__descriptor) \
    , 0, 0, 0,NULL }


struct  Solana__Storage__ConfirmedBlock__InnerInstruction
{
  ProtobufCMessage base;
  protobuf_c_boolean has_program_id_index;
  uint32_t program_id_index;
  protobuf_c_boolean has_accounts;
  ProtobufCBinaryData accounts;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
  /*
   * Invocation stack height of an inner instruction.
   * Available since Solana v1.14.6
   * Set to `None` for txs executed on earlier versions.
   */
  protobuf_c_boolean has_stack_height;
  uint32_t stack_height;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__INNER_INSTRUCTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__inner_instruction__descriptor) \
    , 0, 0, 0, {0,NULL}, 0, {0,NULL}, 0, 0 }


struct  Solana__Storage__ConfirmedBlock__CompiledInstruction
{
  ProtobufCMessage base;
  protobuf_c_boolean has_program_id_index;
  uint32_t program_id_index;
  protobuf_c_boolean has_accounts;
  ProtobufCBinaryData accounts;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__COMPILED_INSTRUCTION__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__compiled_instruction__descriptor) \
    , 0, 0, 0, {0,NULL}, 0, {0,NULL} }


struct  Solana__Storage__ConfirmedBlock__TokenBalance
{
  ProtobufCMessage base;
  protobuf_c_boolean has_account_index;
  uint32_t account_index;
  char *mint;
  Solana__Storage__ConfirmedBlock__UiTokenAmount *ui_token_amount;
  char *owner;
  char *program_id;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__TOKEN_BALANCE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__token_balance__descriptor) \
    , 0, 0, NULL, NULL, NULL, NULL }


struct  Solana__Storage__ConfirmedBlock__UiTokenAmount
{
  ProtobufCMessage base;
  protobuf_c_boolean has_ui_amount;
  double ui_amount;
  protobuf_c_boolean has_decimals;
  uint32_t decimals;
  char *amount;
  char *ui_amount_string;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__UI_TOKEN_AMOUNT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__ui_token_amount__descriptor) \
    , 0, 0, 0, 0, NULL, NULL }


struct  Solana__Storage__ConfirmedBlock__ReturnData
{
  ProtobufCMessage base;
  protobuf_c_boolean has_program_id;
  ProtobufCBinaryData program_id;
  protobuf_c_boolean has_data;
  ProtobufCBinaryData data;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__RETURN_DATA__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__return_data__descriptor) \
    , 0, {0,NULL}, 0, {0,NULL} }


struct  Solana__Storage__ConfirmedBlock__Reward
{
  ProtobufCMessage base;
  char *pubkey;
  protobuf_c_boolean has_lamports;
  int64_t lamports;
  protobuf_c_boolean has_post_balance;
  uint64_t post_balance;
  protobuf_c_boolean has_reward_type;
  Solana__Storage__ConfirmedBlock__RewardType reward_type;
  char *commission;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__reward__descriptor) \
    , NULL, 0, 0, 0, 0, 0, SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Unspecified, NULL }


struct  Solana__Storage__ConfirmedBlock__Rewards
{
  ProtobufCMessage base;
  size_t n_rewards;
  Solana__Storage__ConfirmedBlock__Reward **rewards;
  Solana__Storage__ConfirmedBlock__NumPartitions *num_partitions;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__REWARDS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__rewards__descriptor) \
    , 0,NULL, NULL }


struct  Solana__Storage__ConfirmedBlock__UnixTimestamp
{
  ProtobufCMessage base;
  protobuf_c_boolean has_timestamp;
  int64_t timestamp;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__UNIX_TIMESTAMP__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__unix_timestamp__descriptor) \
    , 0, 0 }


struct  Solana__Storage__ConfirmedBlock__BlockHeight
{
  ProtobufCMessage base;
  protobuf_c_boolean has_block_height;
  uint64_t block_height;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__BLOCK_HEIGHT__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__block_height__descriptor) \
    , 0, 0 }


struct  Solana__Storage__ConfirmedBlock__NumPartitions
{
  ProtobufCMessage base;
  protobuf_c_boolean has_num_partitions;
  uint64_t num_partitions;
};
#define SOLANA__STORAGE__CONFIRMED_BLOCK__NUM_PARTITIONS__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&solana__storage__confirmed_block__num_partitions__descriptor) \
    , 0, 0 }


/* Solana__Storage__ConfirmedBlock__ConfirmedBlock methods */
void   solana__storage__confirmed_block__confirmed_block__init
                     (Solana__Storage__ConfirmedBlock__ConfirmedBlock         *message);
size_t solana__storage__confirmed_block__confirmed_block__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__ConfirmedBlock   *message);
size_t solana__storage__confirmed_block__confirmed_block__pack
                     (const Solana__Storage__ConfirmedBlock__ConfirmedBlock   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__confirmed_block__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__ConfirmedBlock   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__ConfirmedBlock *
       solana__storage__confirmed_block__confirmed_block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__confirmed_block__free_unpacked
                     (Solana__Storage__ConfirmedBlock__ConfirmedBlock *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__ConfirmedTransaction methods */
void   solana__storage__confirmed_block__confirmed_transaction__init
                     (Solana__Storage__ConfirmedBlock__ConfirmedTransaction         *message);
size_t solana__storage__confirmed_block__confirmed_transaction__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__ConfirmedTransaction   *message);
size_t solana__storage__confirmed_block__confirmed_transaction__pack
                     (const Solana__Storage__ConfirmedBlock__ConfirmedTransaction   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__confirmed_transaction__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__ConfirmedTransaction   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__ConfirmedTransaction *
       solana__storage__confirmed_block__confirmed_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__confirmed_transaction__free_unpacked
                     (Solana__Storage__ConfirmedBlock__ConfirmedTransaction *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__Transaction methods */
void   solana__storage__confirmed_block__transaction__init
                     (Solana__Storage__ConfirmedBlock__Transaction         *message);
size_t solana__storage__confirmed_block__transaction__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__Transaction   *message);
size_t solana__storage__confirmed_block__transaction__pack
                     (const Solana__Storage__ConfirmedBlock__Transaction   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__transaction__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__Transaction   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__Transaction *
       solana__storage__confirmed_block__transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__transaction__free_unpacked
                     (Solana__Storage__ConfirmedBlock__Transaction *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__Message methods */
void   solana__storage__confirmed_block__message__init
                     (Solana__Storage__ConfirmedBlock__Message         *message);
size_t solana__storage__confirmed_block__message__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__Message   *message);
size_t solana__storage__confirmed_block__message__pack
                     (const Solana__Storage__ConfirmedBlock__Message   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__message__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__Message   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__Message *
       solana__storage__confirmed_block__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__message__free_unpacked
                     (Solana__Storage__ConfirmedBlock__Message *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__MessageHeader methods */
void   solana__storage__confirmed_block__message_header__init
                     (Solana__Storage__ConfirmedBlock__MessageHeader         *message);
size_t solana__storage__confirmed_block__message_header__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__MessageHeader   *message);
size_t solana__storage__confirmed_block__message_header__pack
                     (const Solana__Storage__ConfirmedBlock__MessageHeader   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__message_header__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__MessageHeader   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__MessageHeader *
       solana__storage__confirmed_block__message_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__message_header__free_unpacked
                     (Solana__Storage__ConfirmedBlock__MessageHeader *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__MessageAddressTableLookup methods */
void   solana__storage__confirmed_block__message_address_table_lookup__init
                     (Solana__Storage__ConfirmedBlock__MessageAddressTableLookup         *message);
size_t solana__storage__confirmed_block__message_address_table_lookup__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__MessageAddressTableLookup   *message);
size_t solana__storage__confirmed_block__message_address_table_lookup__pack
                     (const Solana__Storage__ConfirmedBlock__MessageAddressTableLookup   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__message_address_table_lookup__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__MessageAddressTableLookup   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__MessageAddressTableLookup *
       solana__storage__confirmed_block__message_address_table_lookup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__message_address_table_lookup__free_unpacked
                     (Solana__Storage__ConfirmedBlock__MessageAddressTableLookup *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__TransactionStatusMeta methods */
void   solana__storage__confirmed_block__transaction_status_meta__init
                     (Solana__Storage__ConfirmedBlock__TransactionStatusMeta         *message);
size_t solana__storage__confirmed_block__transaction_status_meta__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__TransactionStatusMeta   *message);
size_t solana__storage__confirmed_block__transaction_status_meta__pack
                     (const Solana__Storage__ConfirmedBlock__TransactionStatusMeta   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__transaction_status_meta__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__TransactionStatusMeta   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__TransactionStatusMeta *
       solana__storage__confirmed_block__transaction_status_meta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__transaction_status_meta__free_unpacked
                     (Solana__Storage__ConfirmedBlock__TransactionStatusMeta *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__TransactionError methods */
void   solana__storage__confirmed_block__transaction_error__init
                     (Solana__Storage__ConfirmedBlock__TransactionError         *message);
size_t solana__storage__confirmed_block__transaction_error__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__TransactionError   *message);
size_t solana__storage__confirmed_block__transaction_error__pack
                     (const Solana__Storage__ConfirmedBlock__TransactionError   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__transaction_error__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__TransactionError   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__TransactionError *
       solana__storage__confirmed_block__transaction_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__transaction_error__free_unpacked
                     (Solana__Storage__ConfirmedBlock__TransactionError *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__InnerInstructions methods */
void   solana__storage__confirmed_block__inner_instructions__init
                     (Solana__Storage__ConfirmedBlock__InnerInstructions         *message);
size_t solana__storage__confirmed_block__inner_instructions__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__InnerInstructions   *message);
size_t solana__storage__confirmed_block__inner_instructions__pack
                     (const Solana__Storage__ConfirmedBlock__InnerInstructions   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__inner_instructions__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__InnerInstructions   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__InnerInstructions *
       solana__storage__confirmed_block__inner_instructions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__inner_instructions__free_unpacked
                     (Solana__Storage__ConfirmedBlock__InnerInstructions *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__InnerInstruction methods */
void   solana__storage__confirmed_block__inner_instruction__init
                     (Solana__Storage__ConfirmedBlock__InnerInstruction         *message);
size_t solana__storage__confirmed_block__inner_instruction__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__InnerInstruction   *message);
size_t solana__storage__confirmed_block__inner_instruction__pack
                     (const Solana__Storage__ConfirmedBlock__InnerInstruction   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__inner_instruction__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__InnerInstruction   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__InnerInstruction *
       solana__storage__confirmed_block__inner_instruction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__inner_instruction__free_unpacked
                     (Solana__Storage__ConfirmedBlock__InnerInstruction *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__CompiledInstruction methods */
void   solana__storage__confirmed_block__compiled_instruction__init
                     (Solana__Storage__ConfirmedBlock__CompiledInstruction         *message);
size_t solana__storage__confirmed_block__compiled_instruction__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__CompiledInstruction   *message);
size_t solana__storage__confirmed_block__compiled_instruction__pack
                     (const Solana__Storage__ConfirmedBlock__CompiledInstruction   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__compiled_instruction__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__CompiledInstruction   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__CompiledInstruction *
       solana__storage__confirmed_block__compiled_instruction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__compiled_instruction__free_unpacked
                     (Solana__Storage__ConfirmedBlock__CompiledInstruction *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__TokenBalance methods */
void   solana__storage__confirmed_block__token_balance__init
                     (Solana__Storage__ConfirmedBlock__TokenBalance         *message);
size_t solana__storage__confirmed_block__token_balance__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__TokenBalance   *message);
size_t solana__storage__confirmed_block__token_balance__pack
                     (const Solana__Storage__ConfirmedBlock__TokenBalance   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__token_balance__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__TokenBalance   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__TokenBalance *
       solana__storage__confirmed_block__token_balance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__token_balance__free_unpacked
                     (Solana__Storage__ConfirmedBlock__TokenBalance *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__UiTokenAmount methods */
void   solana__storage__confirmed_block__ui_token_amount__init
                     (Solana__Storage__ConfirmedBlock__UiTokenAmount         *message);
size_t solana__storage__confirmed_block__ui_token_amount__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__UiTokenAmount   *message);
size_t solana__storage__confirmed_block__ui_token_amount__pack
                     (const Solana__Storage__ConfirmedBlock__UiTokenAmount   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__ui_token_amount__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__UiTokenAmount   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__UiTokenAmount *
       solana__storage__confirmed_block__ui_token_amount__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__ui_token_amount__free_unpacked
                     (Solana__Storage__ConfirmedBlock__UiTokenAmount *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__ReturnData methods */
void   solana__storage__confirmed_block__return_data__init
                     (Solana__Storage__ConfirmedBlock__ReturnData         *message);
size_t solana__storage__confirmed_block__return_data__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__ReturnData   *message);
size_t solana__storage__confirmed_block__return_data__pack
                     (const Solana__Storage__ConfirmedBlock__ReturnData   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__return_data__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__ReturnData   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__ReturnData *
       solana__storage__confirmed_block__return_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__return_data__free_unpacked
                     (Solana__Storage__ConfirmedBlock__ReturnData *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__Reward methods */
void   solana__storage__confirmed_block__reward__init
                     (Solana__Storage__ConfirmedBlock__Reward         *message);
size_t solana__storage__confirmed_block__reward__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__Reward   *message);
size_t solana__storage__confirmed_block__reward__pack
                     (const Solana__Storage__ConfirmedBlock__Reward   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__reward__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__Reward   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__Reward *
       solana__storage__confirmed_block__reward__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__reward__free_unpacked
                     (Solana__Storage__ConfirmedBlock__Reward *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__Rewards methods */
void   solana__storage__confirmed_block__rewards__init
                     (Solana__Storage__ConfirmedBlock__Rewards         *message);
size_t solana__storage__confirmed_block__rewards__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__Rewards   *message);
size_t solana__storage__confirmed_block__rewards__pack
                     (const Solana__Storage__ConfirmedBlock__Rewards   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__rewards__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__Rewards   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__Rewards *
       solana__storage__confirmed_block__rewards__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__rewards__free_unpacked
                     (Solana__Storage__ConfirmedBlock__Rewards *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__UnixTimestamp methods */
void   solana__storage__confirmed_block__unix_timestamp__init
                     (Solana__Storage__ConfirmedBlock__UnixTimestamp         *message);
size_t solana__storage__confirmed_block__unix_timestamp__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__UnixTimestamp   *message);
size_t solana__storage__confirmed_block__unix_timestamp__pack
                     (const Solana__Storage__ConfirmedBlock__UnixTimestamp   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__unix_timestamp__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__UnixTimestamp   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__UnixTimestamp *
       solana__storage__confirmed_block__unix_timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__unix_timestamp__free_unpacked
                     (Solana__Storage__ConfirmedBlock__UnixTimestamp *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__BlockHeight methods */
void   solana__storage__confirmed_block__block_height__init
                     (Solana__Storage__ConfirmedBlock__BlockHeight         *message);
size_t solana__storage__confirmed_block__block_height__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__BlockHeight   *message);
size_t solana__storage__confirmed_block__block_height__pack
                     (const Solana__Storage__ConfirmedBlock__BlockHeight   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__block_height__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__BlockHeight   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__BlockHeight *
       solana__storage__confirmed_block__block_height__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__block_height__free_unpacked
                     (Solana__Storage__ConfirmedBlock__BlockHeight *message,
                      ProtobufCAllocator *allocator);
/* Solana__Storage__ConfirmedBlock__NumPartitions methods */
void   solana__storage__confirmed_block__num_partitions__init
                     (Solana__Storage__ConfirmedBlock__NumPartitions         *message);
size_t solana__storage__confirmed_block__num_partitions__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__NumPartitions   *message);
size_t solana__storage__confirmed_block__num_partitions__pack
                     (const Solana__Storage__ConfirmedBlock__NumPartitions   *message,
                      uint8_t             *out);
size_t solana__storage__confirmed_block__num_partitions__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__NumPartitions   *message,
                      ProtobufCBuffer     *buffer);
Solana__Storage__ConfirmedBlock__NumPartitions *
       solana__storage__confirmed_block__num_partitions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   solana__storage__confirmed_block__num_partitions__free_unpacked
                     (Solana__Storage__ConfirmedBlock__NumPartitions *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*Solana__Storage__ConfirmedBlock__ConfirmedBlock_Closure)
                 (const Solana__Storage__ConfirmedBlock__ConfirmedBlock *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__ConfirmedTransaction_Closure)
                 (const Solana__Storage__ConfirmedBlock__ConfirmedTransaction *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__Transaction_Closure)
                 (const Solana__Storage__ConfirmedBlock__Transaction *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__Message_Closure)
                 (const Solana__Storage__ConfirmedBlock__Message *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__MessageHeader_Closure)
                 (const Solana__Storage__ConfirmedBlock__MessageHeader *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__MessageAddressTableLookup_Closure)
                 (const Solana__Storage__ConfirmedBlock__MessageAddressTableLookup *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__TransactionStatusMeta_Closure)
                 (const Solana__Storage__ConfirmedBlock__TransactionStatusMeta *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__TransactionError_Closure)
                 (const Solana__Storage__ConfirmedBlock__TransactionError *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__InnerInstructions_Closure)
                 (const Solana__Storage__ConfirmedBlock__InnerInstructions *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__InnerInstruction_Closure)
                 (const Solana__Storage__ConfirmedBlock__InnerInstruction *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__CompiledInstruction_Closure)
                 (const Solana__Storage__ConfirmedBlock__CompiledInstruction *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__TokenBalance_Closure)
                 (const Solana__Storage__ConfirmedBlock__TokenBalance *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__UiTokenAmount_Closure)
                 (const Solana__Storage__ConfirmedBlock__UiTokenAmount *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__ReturnData_Closure)
                 (const Solana__Storage__ConfirmedBlock__ReturnData *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__Reward_Closure)
                 (const Solana__Storage__ConfirmedBlock__Reward *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__Rewards_Closure)
                 (const Solana__Storage__ConfirmedBlock__Rewards *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__UnixTimestamp_Closure)
                 (const Solana__Storage__ConfirmedBlock__UnixTimestamp *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__BlockHeight_Closure)
                 (const Solana__Storage__ConfirmedBlock__BlockHeight *message,
                  void *closure_data);
typedef void (*Solana__Storage__ConfirmedBlock__NumPartitions_Closure)
                 (const Solana__Storage__ConfirmedBlock__NumPartitions *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCEnumDescriptor    solana__storage__confirmed_block__reward_type__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__confirmed_block__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__confirmed_transaction__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__transaction__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__message__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__message_header__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__message_address_table_lookup__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__transaction_status_meta__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__transaction_error__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__inner_instructions__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__inner_instruction__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__compiled_instruction__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__token_balance__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__ui_token_amount__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__return_data__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__reward__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__rewards__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__unix_timestamp__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__block_height__descriptor;
extern const ProtobufCMessageDescriptor solana__storage__confirmed_block__num_partitions__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_solana_2dstorage_2eproto__INCLUDED */
