/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: solana-storage.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "solana-storage.pb-c.h"
void   solana__storage__confirmed_block__confirmed_block__init
                     (Solana__Storage__ConfirmedBlock__ConfirmedBlock         *message)
{
  static const Solana__Storage__ConfirmedBlock__ConfirmedBlock init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__CONFIRMED_BLOCK__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__confirmed_block__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__ConfirmedBlock *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__confirmed_block__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__confirmed_block__pack
                     (const Solana__Storage__ConfirmedBlock__ConfirmedBlock *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__confirmed_block__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__confirmed_block__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__ConfirmedBlock *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__confirmed_block__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__ConfirmedBlock *
       solana__storage__confirmed_block__confirmed_block__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__ConfirmedBlock *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__confirmed_block__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__confirmed_block__free_unpacked
                     (Solana__Storage__ConfirmedBlock__ConfirmedBlock *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__confirmed_block__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__confirmed_transaction__init
                     (Solana__Storage__ConfirmedBlock__ConfirmedTransaction         *message)
{
  static const Solana__Storage__ConfirmedBlock__ConfirmedTransaction init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__CONFIRMED_TRANSACTION__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__confirmed_transaction__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__ConfirmedTransaction *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__confirmed_transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__confirmed_transaction__pack
                     (const Solana__Storage__ConfirmedBlock__ConfirmedTransaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__confirmed_transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__confirmed_transaction__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__ConfirmedTransaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__confirmed_transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__ConfirmedTransaction *
       solana__storage__confirmed_block__confirmed_transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__ConfirmedTransaction *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__confirmed_transaction__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__confirmed_transaction__free_unpacked
                     (Solana__Storage__ConfirmedBlock__ConfirmedTransaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__confirmed_transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__transaction__init
                     (Solana__Storage__ConfirmedBlock__Transaction         *message)
{
  static const Solana__Storage__ConfirmedBlock__Transaction init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__TRANSACTION__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__transaction__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__Transaction *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__transaction__pack
                     (const Solana__Storage__ConfirmedBlock__Transaction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__transaction__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__Transaction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__Transaction *
       solana__storage__confirmed_block__transaction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__Transaction *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__transaction__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__transaction__free_unpacked
                     (Solana__Storage__ConfirmedBlock__Transaction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__message__init
                     (Solana__Storage__ConfirmedBlock__Message         *message)
{
  static const Solana__Storage__ConfirmedBlock__Message init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__MESSAGE__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__message__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__Message *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__message__pack
                     (const Solana__Storage__ConfirmedBlock__Message *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__message__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__Message *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__Message *
       solana__storage__confirmed_block__message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__Message *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__message__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__message__free_unpacked
                     (Solana__Storage__ConfirmedBlock__Message *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__message_header__init
                     (Solana__Storage__ConfirmedBlock__MessageHeader         *message)
{
  static const Solana__Storage__ConfirmedBlock__MessageHeader init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__MESSAGE_HEADER__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__message_header__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__MessageHeader *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__message_header__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__message_header__pack
                     (const Solana__Storage__ConfirmedBlock__MessageHeader *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__message_header__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__message_header__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__MessageHeader *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__message_header__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__MessageHeader *
       solana__storage__confirmed_block__message_header__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__MessageHeader *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__message_header__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__message_header__free_unpacked
                     (Solana__Storage__ConfirmedBlock__MessageHeader *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__message_header__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__message_address_table_lookup__init
                     (Solana__Storage__ConfirmedBlock__MessageAddressTableLookup         *message)
{
  static const Solana__Storage__ConfirmedBlock__MessageAddressTableLookup init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__MESSAGE_ADDRESS_TABLE_LOOKUP__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__message_address_table_lookup__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__MessageAddressTableLookup *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__message_address_table_lookup__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__message_address_table_lookup__pack
                     (const Solana__Storage__ConfirmedBlock__MessageAddressTableLookup *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__message_address_table_lookup__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__message_address_table_lookup__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__MessageAddressTableLookup *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__message_address_table_lookup__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__MessageAddressTableLookup *
       solana__storage__confirmed_block__message_address_table_lookup__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__MessageAddressTableLookup *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__message_address_table_lookup__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__message_address_table_lookup__free_unpacked
                     (Solana__Storage__ConfirmedBlock__MessageAddressTableLookup *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__message_address_table_lookup__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__transaction_status_meta__init
                     (Solana__Storage__ConfirmedBlock__TransactionStatusMeta         *message)
{
  static const Solana__Storage__ConfirmedBlock__TransactionStatusMeta init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__TRANSACTION_STATUS_META__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__transaction_status_meta__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__TransactionStatusMeta *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction_status_meta__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__transaction_status_meta__pack
                     (const Solana__Storage__ConfirmedBlock__TransactionStatusMeta *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction_status_meta__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__transaction_status_meta__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__TransactionStatusMeta *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction_status_meta__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__TransactionStatusMeta *
       solana__storage__confirmed_block__transaction_status_meta__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__TransactionStatusMeta *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__transaction_status_meta__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__transaction_status_meta__free_unpacked
                     (Solana__Storage__ConfirmedBlock__TransactionStatusMeta *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction_status_meta__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__transaction_error__init
                     (Solana__Storage__ConfirmedBlock__TransactionError         *message)
{
  static const Solana__Storage__ConfirmedBlock__TransactionError init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__TRANSACTION_ERROR__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__transaction_error__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__TransactionError *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__transaction_error__pack
                     (const Solana__Storage__ConfirmedBlock__TransactionError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__transaction_error__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__TransactionError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__TransactionError *
       solana__storage__confirmed_block__transaction_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__TransactionError *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__transaction_error__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__transaction_error__free_unpacked
                     (Solana__Storage__ConfirmedBlock__TransactionError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__transaction_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__inner_instructions__init
                     (Solana__Storage__ConfirmedBlock__InnerInstructions         *message)
{
  static const Solana__Storage__ConfirmedBlock__InnerInstructions init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__INNER_INSTRUCTIONS__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__inner_instructions__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__InnerInstructions *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__inner_instructions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__inner_instructions__pack
                     (const Solana__Storage__ConfirmedBlock__InnerInstructions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__inner_instructions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__inner_instructions__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__InnerInstructions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__inner_instructions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__InnerInstructions *
       solana__storage__confirmed_block__inner_instructions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__InnerInstructions *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__inner_instructions__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__inner_instructions__free_unpacked
                     (Solana__Storage__ConfirmedBlock__InnerInstructions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__inner_instructions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__inner_instruction__init
                     (Solana__Storage__ConfirmedBlock__InnerInstruction         *message)
{
  static const Solana__Storage__ConfirmedBlock__InnerInstruction init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__INNER_INSTRUCTION__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__inner_instruction__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__InnerInstruction *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__inner_instruction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__inner_instruction__pack
                     (const Solana__Storage__ConfirmedBlock__InnerInstruction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__inner_instruction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__inner_instruction__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__InnerInstruction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__inner_instruction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__InnerInstruction *
       solana__storage__confirmed_block__inner_instruction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__InnerInstruction *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__inner_instruction__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__inner_instruction__free_unpacked
                     (Solana__Storage__ConfirmedBlock__InnerInstruction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__inner_instruction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__compiled_instruction__init
                     (Solana__Storage__ConfirmedBlock__CompiledInstruction         *message)
{
  static const Solana__Storage__ConfirmedBlock__CompiledInstruction init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__COMPILED_INSTRUCTION__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__compiled_instruction__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__CompiledInstruction *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__compiled_instruction__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__compiled_instruction__pack
                     (const Solana__Storage__ConfirmedBlock__CompiledInstruction *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__compiled_instruction__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__compiled_instruction__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__CompiledInstruction *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__compiled_instruction__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__CompiledInstruction *
       solana__storage__confirmed_block__compiled_instruction__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__CompiledInstruction *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__compiled_instruction__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__compiled_instruction__free_unpacked
                     (Solana__Storage__ConfirmedBlock__CompiledInstruction *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__compiled_instruction__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__token_balance__init
                     (Solana__Storage__ConfirmedBlock__TokenBalance         *message)
{
  static const Solana__Storage__ConfirmedBlock__TokenBalance init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__TOKEN_BALANCE__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__token_balance__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__TokenBalance *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__token_balance__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__token_balance__pack
                     (const Solana__Storage__ConfirmedBlock__TokenBalance *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__token_balance__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__token_balance__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__TokenBalance *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__token_balance__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__TokenBalance *
       solana__storage__confirmed_block__token_balance__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__TokenBalance *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__token_balance__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__token_balance__free_unpacked
                     (Solana__Storage__ConfirmedBlock__TokenBalance *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__token_balance__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__ui_token_amount__init
                     (Solana__Storage__ConfirmedBlock__UiTokenAmount         *message)
{
  static const Solana__Storage__ConfirmedBlock__UiTokenAmount init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__UI_TOKEN_AMOUNT__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__ui_token_amount__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__UiTokenAmount *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__ui_token_amount__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__ui_token_amount__pack
                     (const Solana__Storage__ConfirmedBlock__UiTokenAmount *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__ui_token_amount__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__ui_token_amount__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__UiTokenAmount *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__ui_token_amount__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__UiTokenAmount *
       solana__storage__confirmed_block__ui_token_amount__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__UiTokenAmount *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__ui_token_amount__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__ui_token_amount__free_unpacked
                     (Solana__Storage__ConfirmedBlock__UiTokenAmount *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__ui_token_amount__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__return_data__init
                     (Solana__Storage__ConfirmedBlock__ReturnData         *message)
{
  static const Solana__Storage__ConfirmedBlock__ReturnData init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__RETURN_DATA__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__return_data__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__ReturnData *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__return_data__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__return_data__pack
                     (const Solana__Storage__ConfirmedBlock__ReturnData *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__return_data__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__return_data__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__ReturnData *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__return_data__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__ReturnData *
       solana__storage__confirmed_block__return_data__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__ReturnData *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__return_data__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__return_data__free_unpacked
                     (Solana__Storage__ConfirmedBlock__ReturnData *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__return_data__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__reward__init
                     (Solana__Storage__ConfirmedBlock__Reward         *message)
{
  static const Solana__Storage__ConfirmedBlock__Reward init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__reward__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__Reward *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__reward__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__reward__pack
                     (const Solana__Storage__ConfirmedBlock__Reward *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__reward__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__reward__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__Reward *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__reward__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__Reward *
       solana__storage__confirmed_block__reward__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__Reward *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__reward__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__reward__free_unpacked
                     (Solana__Storage__ConfirmedBlock__Reward *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__reward__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__rewards__init
                     (Solana__Storage__ConfirmedBlock__Rewards         *message)
{
  static const Solana__Storage__ConfirmedBlock__Rewards init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__REWARDS__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__rewards__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__Rewards *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__rewards__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__rewards__pack
                     (const Solana__Storage__ConfirmedBlock__Rewards *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__rewards__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__rewards__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__Rewards *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__rewards__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__Rewards *
       solana__storage__confirmed_block__rewards__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__Rewards *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__rewards__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__rewards__free_unpacked
                     (Solana__Storage__ConfirmedBlock__Rewards *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__rewards__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__unix_timestamp__init
                     (Solana__Storage__ConfirmedBlock__UnixTimestamp         *message)
{
  static const Solana__Storage__ConfirmedBlock__UnixTimestamp init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__UNIX_TIMESTAMP__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__unix_timestamp__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__UnixTimestamp *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__unix_timestamp__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__unix_timestamp__pack
                     (const Solana__Storage__ConfirmedBlock__UnixTimestamp *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__unix_timestamp__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__unix_timestamp__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__UnixTimestamp *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__unix_timestamp__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__UnixTimestamp *
       solana__storage__confirmed_block__unix_timestamp__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__UnixTimestamp *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__unix_timestamp__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__unix_timestamp__free_unpacked
                     (Solana__Storage__ConfirmedBlock__UnixTimestamp *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__unix_timestamp__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__block_height__init
                     (Solana__Storage__ConfirmedBlock__BlockHeight         *message)
{
  static const Solana__Storage__ConfirmedBlock__BlockHeight init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__BLOCK_HEIGHT__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__block_height__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__BlockHeight *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__block_height__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__block_height__pack
                     (const Solana__Storage__ConfirmedBlock__BlockHeight *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__block_height__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__block_height__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__BlockHeight *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__block_height__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__BlockHeight *
       solana__storage__confirmed_block__block_height__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__BlockHeight *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__block_height__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__block_height__free_unpacked
                     (Solana__Storage__ConfirmedBlock__BlockHeight *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__block_height__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   solana__storage__confirmed_block__num_partitions__init
                     (Solana__Storage__ConfirmedBlock__NumPartitions         *message)
{
  static const Solana__Storage__ConfirmedBlock__NumPartitions init_value = SOLANA__STORAGE__CONFIRMED_BLOCK__NUM_PARTITIONS__INIT;
  *message = init_value;
}
size_t solana__storage__confirmed_block__num_partitions__get_packed_size
                     (const Solana__Storage__ConfirmedBlock__NumPartitions *message)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__num_partitions__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t solana__storage__confirmed_block__num_partitions__pack
                     (const Solana__Storage__ConfirmedBlock__NumPartitions *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__num_partitions__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t solana__storage__confirmed_block__num_partitions__pack_to_buffer
                     (const Solana__Storage__ConfirmedBlock__NumPartitions *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &solana__storage__confirmed_block__num_partitions__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Solana__Storage__ConfirmedBlock__NumPartitions *
       solana__storage__confirmed_block__num_partitions__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Solana__Storage__ConfirmedBlock__NumPartitions *)
     protobuf_c_message_unpack (&solana__storage__confirmed_block__num_partitions__descriptor,
                                allocator, len, data);
}
void   solana__storage__confirmed_block__num_partitions__free_unpacked
                     (Solana__Storage__ConfirmedBlock__NumPartitions *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &solana__storage__confirmed_block__num_partitions__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__confirmed_block__field_descriptors[8] =
{
  {
    "previous_blockhash",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, previous_blockhash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "blockhash",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, blockhash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "parent_slot",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, has_parent_slot),
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, parent_slot),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "transactions",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, n_transactions),
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, transactions),
    &solana__storage__confirmed_block__confirmed_transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rewards",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, n_rewards),
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, rewards),
    &solana__storage__confirmed_block__reward__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_time",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, block_time),
    &solana__storage__confirmed_block__unix_timestamp__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "block_height",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, block_height),
    &solana__storage__confirmed_block__block_height__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_partitions",
    8,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedBlock, num_partitions),
    &solana__storage__confirmed_block__num_partitions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__confirmed_block__field_indices_by_name[] = {
  6,   /* field[6] = block_height */
  5,   /* field[5] = block_time */
  1,   /* field[1] = blockhash */
  7,   /* field[7] = num_partitions */
  2,   /* field[2] = parent_slot */
  0,   /* field[0] = previous_blockhash */
  4,   /* field[4] = rewards */
  3,   /* field[3] = transactions */
};
static const ProtobufCIntRange solana__storage__confirmed_block__confirmed_block__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 8 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__confirmed_block__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.ConfirmedBlock",
  "ConfirmedBlock",
  "Solana__Storage__ConfirmedBlock__ConfirmedBlock",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__ConfirmedBlock),
  8,
  solana__storage__confirmed_block__confirmed_block__field_descriptors,
  solana__storage__confirmed_block__confirmed_block__field_indices_by_name,
  1,  solana__storage__confirmed_block__confirmed_block__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__confirmed_block__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__confirmed_transaction__field_descriptors[2] =
{
  {
    "transaction",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedTransaction, transaction),
    &solana__storage__confirmed_block__transaction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "meta",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__ConfirmedTransaction, meta),
    &solana__storage__confirmed_block__transaction_status_meta__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__confirmed_transaction__field_indices_by_name[] = {
  1,   /* field[1] = meta */
  0,   /* field[0] = transaction */
};
static const ProtobufCIntRange solana__storage__confirmed_block__confirmed_transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__confirmed_transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.ConfirmedTransaction",
  "ConfirmedTransaction",
  "Solana__Storage__ConfirmedBlock__ConfirmedTransaction",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__ConfirmedTransaction),
  2,
  solana__storage__confirmed_block__confirmed_transaction__field_descriptors,
  solana__storage__confirmed_block__confirmed_transaction__field_indices_by_name,
  1,  solana__storage__confirmed_block__confirmed_transaction__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__confirmed_transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__transaction__field_descriptors[2] =
{
  {
    "signatures",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__Transaction, n_signatures),
    offsetof(Solana__Storage__ConfirmedBlock__Transaction, signatures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "message",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__Transaction, message),
    &solana__storage__confirmed_block__message__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__transaction__field_indices_by_name[] = {
  1,   /* field[1] = message */
  0,   /* field[0] = signatures */
};
static const ProtobufCIntRange solana__storage__confirmed_block__transaction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__transaction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.Transaction",
  "Transaction",
  "Solana__Storage__ConfirmedBlock__Transaction",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__Transaction),
  2,
  solana__storage__confirmed_block__transaction__field_descriptors,
  solana__storage__confirmed_block__transaction__field_indices_by_name,
  1,  solana__storage__confirmed_block__transaction__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__transaction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__message__field_descriptors[6] =
{
  {
    "header",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__Message, header),
    &solana__storage__confirmed_block__message_header__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "account_keys",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__Message, n_account_keys),
    offsetof(Solana__Storage__ConfirmedBlock__Message, account_keys),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "recent_blockhash",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__Message, has_recent_blockhash),
    offsetof(Solana__Storage__ConfirmedBlock__Message, recent_blockhash),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instructions",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__Message, n_instructions),
    offsetof(Solana__Storage__ConfirmedBlock__Message, instructions),
    &solana__storage__confirmed_block__compiled_instruction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "versioned",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Solana__Storage__ConfirmedBlock__Message, has_versioned),
    offsetof(Solana__Storage__ConfirmedBlock__Message, versioned),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "address_table_lookups",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__Message, n_address_table_lookups),
    offsetof(Solana__Storage__ConfirmedBlock__Message, address_table_lookups),
    &solana__storage__confirmed_block__message_address_table_lookup__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__message__field_indices_by_name[] = {
  1,   /* field[1] = account_keys */
  5,   /* field[5] = address_table_lookups */
  0,   /* field[0] = header */
  3,   /* field[3] = instructions */
  2,   /* field[2] = recent_blockhash */
  4,   /* field[4] = versioned */
};
static const ProtobufCIntRange solana__storage__confirmed_block__message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 6 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.Message",
  "Message",
  "Solana__Storage__ConfirmedBlock__Message",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__Message),
  6,
  solana__storage__confirmed_block__message__field_descriptors,
  solana__storage__confirmed_block__message__field_indices_by_name,
  1,  solana__storage__confirmed_block__message__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__message_header__field_descriptors[3] =
{
  {
    "num_required_signatures",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Solana__Storage__ConfirmedBlock__MessageHeader, has_num_required_signatures),
    offsetof(Solana__Storage__ConfirmedBlock__MessageHeader, num_required_signatures),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_readonly_signed_accounts",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Solana__Storage__ConfirmedBlock__MessageHeader, has_num_readonly_signed_accounts),
    offsetof(Solana__Storage__ConfirmedBlock__MessageHeader, num_readonly_signed_accounts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_readonly_unsigned_accounts",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Solana__Storage__ConfirmedBlock__MessageHeader, has_num_readonly_unsigned_accounts),
    offsetof(Solana__Storage__ConfirmedBlock__MessageHeader, num_readonly_unsigned_accounts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__message_header__field_indices_by_name[] = {
  1,   /* field[1] = num_readonly_signed_accounts */
  2,   /* field[2] = num_readonly_unsigned_accounts */
  0,   /* field[0] = num_required_signatures */
};
static const ProtobufCIntRange solana__storage__confirmed_block__message_header__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__message_header__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.MessageHeader",
  "MessageHeader",
  "Solana__Storage__ConfirmedBlock__MessageHeader",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__MessageHeader),
  3,
  solana__storage__confirmed_block__message_header__field_descriptors,
  solana__storage__confirmed_block__message_header__field_indices_by_name,
  1,  solana__storage__confirmed_block__message_header__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__message_header__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__message_address_table_lookup__field_descriptors[3] =
{
  {
    "account_key",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__MessageAddressTableLookup, has_account_key),
    offsetof(Solana__Storage__ConfirmedBlock__MessageAddressTableLookup, account_key),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "writable_indexes",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__MessageAddressTableLookup, has_writable_indexes),
    offsetof(Solana__Storage__ConfirmedBlock__MessageAddressTableLookup, writable_indexes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "readonly_indexes",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__MessageAddressTableLookup, has_readonly_indexes),
    offsetof(Solana__Storage__ConfirmedBlock__MessageAddressTableLookup, readonly_indexes),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__message_address_table_lookup__field_indices_by_name[] = {
  0,   /* field[0] = account_key */
  2,   /* field[2] = readonly_indexes */
  1,   /* field[1] = writable_indexes */
};
static const ProtobufCIntRange solana__storage__confirmed_block__message_address_table_lookup__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__message_address_table_lookup__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.MessageAddressTableLookup",
  "MessageAddressTableLookup",
  "Solana__Storage__ConfirmedBlock__MessageAddressTableLookup",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__MessageAddressTableLookup),
  3,
  solana__storage__confirmed_block__message_address_table_lookup__field_descriptors,
  solana__storage__confirmed_block__message_address_table_lookup__field_indices_by_name,
  1,  solana__storage__confirmed_block__message_address_table_lookup__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__message_address_table_lookup__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__transaction_status_meta__field_descriptors[17] =
{
  {
    "err",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, err),
    &solana__storage__confirmed_block__transaction_error__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "fee",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, has_fee),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, fee),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pre_balances",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, n_pre_balances),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, pre_balances),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "post_balances",
    4,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, n_post_balances),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, post_balances),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_instructions",
    5,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, n_inner_instructions),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, inner_instructions),
    &solana__storage__confirmed_block__inner_instructions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_messages",
    6,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_STRING,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, n_log_messages),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, log_messages),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "pre_token_balances",
    7,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, n_pre_token_balances),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, pre_token_balances),
    &solana__storage__confirmed_block__token_balance__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "post_token_balances",
    8,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, n_post_token_balances),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, post_token_balances),
    &solana__storage__confirmed_block__token_balance__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "rewards",
    9,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, n_rewards),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, rewards),
    &solana__storage__confirmed_block__reward__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "inner_instructions_none",
    10,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, has_inner_instructions_none),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, inner_instructions_none),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "log_messages_none",
    11,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, has_log_messages_none),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, log_messages_none),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loaded_writable_addresses",
    12,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, n_loaded_writable_addresses),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, loaded_writable_addresses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "loaded_readonly_addresses",
    13,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, n_loaded_readonly_addresses),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, loaded_readonly_addresses),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_data",
    14,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, return_data),
    &solana__storage__confirmed_block__return_data__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "return_data_none",
    15,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BOOL,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, has_return_data_none),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, return_data_none),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "compute_units_consumed",
    16,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, has_compute_units_consumed),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, compute_units_consumed),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "cost_units",
    17,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, has_cost_units),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta, cost_units),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__transaction_status_meta__field_indices_by_name[] = {
  15,   /* field[15] = compute_units_consumed */
  16,   /* field[16] = cost_units */
  0,   /* field[0] = err */
  1,   /* field[1] = fee */
  4,   /* field[4] = inner_instructions */
  9,   /* field[9] = inner_instructions_none */
  12,   /* field[12] = loaded_readonly_addresses */
  11,   /* field[11] = loaded_writable_addresses */
  5,   /* field[5] = log_messages */
  10,   /* field[10] = log_messages_none */
  3,   /* field[3] = post_balances */
  7,   /* field[7] = post_token_balances */
  2,   /* field[2] = pre_balances */
  6,   /* field[6] = pre_token_balances */
  13,   /* field[13] = return_data */
  14,   /* field[14] = return_data_none */
  8,   /* field[8] = rewards */
};
static const ProtobufCIntRange solana__storage__confirmed_block__transaction_status_meta__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 17 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__transaction_status_meta__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.TransactionStatusMeta",
  "TransactionStatusMeta",
  "Solana__Storage__ConfirmedBlock__TransactionStatusMeta",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__TransactionStatusMeta),
  17,
  solana__storage__confirmed_block__transaction_status_meta__field_descriptors,
  solana__storage__confirmed_block__transaction_status_meta__field_indices_by_name,
  1,  solana__storage__confirmed_block__transaction_status_meta__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__transaction_status_meta__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__transaction_error__field_descriptors[1] =
{
  {
    "err",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__TransactionError, has_err),
    offsetof(Solana__Storage__ConfirmedBlock__TransactionError, err),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__transaction_error__field_indices_by_name[] = {
  0,   /* field[0] = err */
};
static const ProtobufCIntRange solana__storage__confirmed_block__transaction_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__transaction_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.TransactionError",
  "TransactionError",
  "Solana__Storage__ConfirmedBlock__TransactionError",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__TransactionError),
  1,
  solana__storage__confirmed_block__transaction_error__field_descriptors,
  solana__storage__confirmed_block__transaction_error__field_indices_by_name,
  1,  solana__storage__confirmed_block__transaction_error__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__transaction_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__inner_instructions__field_descriptors[2] =
{
  {
    "index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstructions, has_index),
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstructions, index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "instructions",
    2,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstructions, n_instructions),
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstructions, instructions),
    &solana__storage__confirmed_block__inner_instruction__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__inner_instructions__field_indices_by_name[] = {
  0,   /* field[0] = index */
  1,   /* field[1] = instructions */
};
static const ProtobufCIntRange solana__storage__confirmed_block__inner_instructions__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__inner_instructions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.InnerInstructions",
  "InnerInstructions",
  "Solana__Storage__ConfirmedBlock__InnerInstructions",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__InnerInstructions),
  2,
  solana__storage__confirmed_block__inner_instructions__field_descriptors,
  solana__storage__confirmed_block__inner_instructions__field_indices_by_name,
  1,  solana__storage__confirmed_block__inner_instructions__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__inner_instructions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__inner_instruction__field_descriptors[4] =
{
  {
    "program_id_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstruction, has_program_id_index),
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstruction, program_id_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accounts",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstruction, has_accounts),
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstruction, accounts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstruction, has_data),
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstruction, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "stack_height",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstruction, has_stack_height),
    offsetof(Solana__Storage__ConfirmedBlock__InnerInstruction, stack_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__inner_instruction__field_indices_by_name[] = {
  1,   /* field[1] = accounts */
  2,   /* field[2] = data */
  0,   /* field[0] = program_id_index */
  3,   /* field[3] = stack_height */
};
static const ProtobufCIntRange solana__storage__confirmed_block__inner_instruction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__inner_instruction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.InnerInstruction",
  "InnerInstruction",
  "Solana__Storage__ConfirmedBlock__InnerInstruction",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__InnerInstruction),
  4,
  solana__storage__confirmed_block__inner_instruction__field_descriptors,
  solana__storage__confirmed_block__inner_instruction__field_indices_by_name,
  1,  solana__storage__confirmed_block__inner_instruction__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__inner_instruction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__compiled_instruction__field_descriptors[3] =
{
  {
    "program_id_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Solana__Storage__ConfirmedBlock__CompiledInstruction, has_program_id_index),
    offsetof(Solana__Storage__ConfirmedBlock__CompiledInstruction, program_id_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "accounts",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__CompiledInstruction, has_accounts),
    offsetof(Solana__Storage__ConfirmedBlock__CompiledInstruction, accounts),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__CompiledInstruction, has_data),
    offsetof(Solana__Storage__ConfirmedBlock__CompiledInstruction, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__compiled_instruction__field_indices_by_name[] = {
  1,   /* field[1] = accounts */
  2,   /* field[2] = data */
  0,   /* field[0] = program_id_index */
};
static const ProtobufCIntRange solana__storage__confirmed_block__compiled_instruction__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__compiled_instruction__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.CompiledInstruction",
  "CompiledInstruction",
  "Solana__Storage__ConfirmedBlock__CompiledInstruction",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__CompiledInstruction),
  3,
  solana__storage__confirmed_block__compiled_instruction__field_descriptors,
  solana__storage__confirmed_block__compiled_instruction__field_indices_by_name,
  1,  solana__storage__confirmed_block__compiled_instruction__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__compiled_instruction__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__token_balance__field_descriptors[5] =
{
  {
    "account_index",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Solana__Storage__ConfirmedBlock__TokenBalance, has_account_index),
    offsetof(Solana__Storage__ConfirmedBlock__TokenBalance, account_index),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "mint",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__TokenBalance, mint),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ui_token_amount",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__TokenBalance, ui_token_amount),
    &solana__storage__confirmed_block__ui_token_amount__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "owner",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__TokenBalance, owner),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "program_id",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__TokenBalance, program_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__token_balance__field_indices_by_name[] = {
  0,   /* field[0] = account_index */
  1,   /* field[1] = mint */
  3,   /* field[3] = owner */
  4,   /* field[4] = program_id */
  2,   /* field[2] = ui_token_amount */
};
static const ProtobufCIntRange solana__storage__confirmed_block__token_balance__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__token_balance__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.TokenBalance",
  "TokenBalance",
  "Solana__Storage__ConfirmedBlock__TokenBalance",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__TokenBalance),
  5,
  solana__storage__confirmed_block__token_balance__field_descriptors,
  solana__storage__confirmed_block__token_balance__field_indices_by_name,
  1,  solana__storage__confirmed_block__token_balance__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__token_balance__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__ui_token_amount__field_descriptors[4] =
{
  {
    "ui_amount",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_DOUBLE,
    offsetof(Solana__Storage__ConfirmedBlock__UiTokenAmount, has_ui_amount),
    offsetof(Solana__Storage__ConfirmedBlock__UiTokenAmount, ui_amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "decimals",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT32,
    offsetof(Solana__Storage__ConfirmedBlock__UiTokenAmount, has_decimals),
    offsetof(Solana__Storage__ConfirmedBlock__UiTokenAmount, decimals),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "amount",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__UiTokenAmount, amount),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "ui_amount_string",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__UiTokenAmount, ui_amount_string),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__ui_token_amount__field_indices_by_name[] = {
  2,   /* field[2] = amount */
  1,   /* field[1] = decimals */
  0,   /* field[0] = ui_amount */
  3,   /* field[3] = ui_amount_string */
};
static const ProtobufCIntRange solana__storage__confirmed_block__ui_token_amount__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 4 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__ui_token_amount__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.UiTokenAmount",
  "UiTokenAmount",
  "Solana__Storage__ConfirmedBlock__UiTokenAmount",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__UiTokenAmount),
  4,
  solana__storage__confirmed_block__ui_token_amount__field_descriptors,
  solana__storage__confirmed_block__ui_token_amount__field_indices_by_name,
  1,  solana__storage__confirmed_block__ui_token_amount__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__ui_token_amount__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__return_data__field_descriptors[2] =
{
  {
    "program_id",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__ReturnData, has_program_id),
    offsetof(Solana__Storage__ConfirmedBlock__ReturnData, program_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "data",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Solana__Storage__ConfirmedBlock__ReturnData, has_data),
    offsetof(Solana__Storage__ConfirmedBlock__ReturnData, data),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__return_data__field_indices_by_name[] = {
  1,   /* field[1] = data */
  0,   /* field[0] = program_id */
};
static const ProtobufCIntRange solana__storage__confirmed_block__return_data__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__return_data__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.ReturnData",
  "ReturnData",
  "Solana__Storage__ConfirmedBlock__ReturnData",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__ReturnData),
  2,
  solana__storage__confirmed_block__return_data__field_descriptors,
  solana__storage__confirmed_block__return_data__field_indices_by_name,
  1,  solana__storage__confirmed_block__return_data__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__return_data__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__reward__field_descriptors[5] =
{
  {
    "pubkey",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__Reward, pubkey),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "lamports",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Solana__Storage__ConfirmedBlock__Reward, has_lamports),
    offsetof(Solana__Storage__ConfirmedBlock__Reward, lamports),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "post_balance",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Solana__Storage__ConfirmedBlock__Reward, has_post_balance),
    offsetof(Solana__Storage__ConfirmedBlock__Reward, post_balance),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "reward_type",
    4,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_ENUM,
    offsetof(Solana__Storage__ConfirmedBlock__Reward, has_reward_type),
    offsetof(Solana__Storage__ConfirmedBlock__Reward, reward_type),
    &solana__storage__confirmed_block__reward_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "commission",
    5,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__Reward, commission),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__reward__field_indices_by_name[] = {
  4,   /* field[4] = commission */
  1,   /* field[1] = lamports */
  2,   /* field[2] = post_balance */
  0,   /* field[0] = pubkey */
  3,   /* field[3] = reward_type */
};
static const ProtobufCIntRange solana__storage__confirmed_block__reward__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 5 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__reward__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.Reward",
  "Reward",
  "Solana__Storage__ConfirmedBlock__Reward",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__Reward),
  5,
  solana__storage__confirmed_block__reward__field_descriptors,
  solana__storage__confirmed_block__reward__field_indices_by_name,
  1,  solana__storage__confirmed_block__reward__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__reward__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__rewards__field_descriptors[2] =
{
  {
    "rewards",
    1,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_MESSAGE,
    offsetof(Solana__Storage__ConfirmedBlock__Rewards, n_rewards),
    offsetof(Solana__Storage__ConfirmedBlock__Rewards, rewards),
    &solana__storage__confirmed_block__reward__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "num_partitions",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(Solana__Storage__ConfirmedBlock__Rewards, num_partitions),
    &solana__storage__confirmed_block__num_partitions__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__rewards__field_indices_by_name[] = {
  1,   /* field[1] = num_partitions */
  0,   /* field[0] = rewards */
};
static const ProtobufCIntRange solana__storage__confirmed_block__rewards__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 2 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__rewards__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.Rewards",
  "Rewards",
  "Solana__Storage__ConfirmedBlock__Rewards",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__Rewards),
  2,
  solana__storage__confirmed_block__rewards__field_descriptors,
  solana__storage__confirmed_block__rewards__field_indices_by_name,
  1,  solana__storage__confirmed_block__rewards__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__rewards__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__unix_timestamp__field_descriptors[1] =
{
  {
    "timestamp",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT64,
    offsetof(Solana__Storage__ConfirmedBlock__UnixTimestamp, has_timestamp),
    offsetof(Solana__Storage__ConfirmedBlock__UnixTimestamp, timestamp),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__unix_timestamp__field_indices_by_name[] = {
  0,   /* field[0] = timestamp */
};
static const ProtobufCIntRange solana__storage__confirmed_block__unix_timestamp__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__unix_timestamp__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.UnixTimestamp",
  "UnixTimestamp",
  "Solana__Storage__ConfirmedBlock__UnixTimestamp",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__UnixTimestamp),
  1,
  solana__storage__confirmed_block__unix_timestamp__field_descriptors,
  solana__storage__confirmed_block__unix_timestamp__field_indices_by_name,
  1,  solana__storage__confirmed_block__unix_timestamp__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__unix_timestamp__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__block_height__field_descriptors[1] =
{
  {
    "block_height",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Solana__Storage__ConfirmedBlock__BlockHeight, has_block_height),
    offsetof(Solana__Storage__ConfirmedBlock__BlockHeight, block_height),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__block_height__field_indices_by_name[] = {
  0,   /* field[0] = block_height */
};
static const ProtobufCIntRange solana__storage__confirmed_block__block_height__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__block_height__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.BlockHeight",
  "BlockHeight",
  "Solana__Storage__ConfirmedBlock__BlockHeight",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__BlockHeight),
  1,
  solana__storage__confirmed_block__block_height__field_descriptors,
  solana__storage__confirmed_block__block_height__field_indices_by_name,
  1,  solana__storage__confirmed_block__block_height__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__block_height__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor solana__storage__confirmed_block__num_partitions__field_descriptors[1] =
{
  {
    "num_partitions",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_UINT64,
    offsetof(Solana__Storage__ConfirmedBlock__NumPartitions, has_num_partitions),
    offsetof(Solana__Storage__ConfirmedBlock__NumPartitions, num_partitions),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned solana__storage__confirmed_block__num_partitions__field_indices_by_name[] = {
  0,   /* field[0] = num_partitions */
};
static const ProtobufCIntRange solana__storage__confirmed_block__num_partitions__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor solana__storage__confirmed_block__num_partitions__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.NumPartitions",
  "NumPartitions",
  "Solana__Storage__ConfirmedBlock__NumPartitions",
  "solana.storage.ConfirmedBlock",
  sizeof(Solana__Storage__ConfirmedBlock__NumPartitions),
  1,
  solana__storage__confirmed_block__num_partitions__field_descriptors,
  solana__storage__confirmed_block__num_partitions__field_indices_by_name,
  1,  solana__storage__confirmed_block__num_partitions__number_ranges,
  (ProtobufCMessageInit) solana__storage__confirmed_block__num_partitions__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue solana__storage__confirmed_block__reward_type__enum_values_by_number[5] =
{
  { "Unspecified", "SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Unspecified", 0 },
  { "Fee", "SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Fee", 1 },
  { "Rent", "SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Rent", 2 },
  { "Staking", "SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Staking", 3 },
  { "Voting", "SOLANA__STORAGE__CONFIRMED_BLOCK__REWARD_TYPE__Voting", 4 },
};
static const ProtobufCIntRange solana__storage__confirmed_block__reward_type__value_ranges[] = {
{0, 0},{0, 5}
};
static const ProtobufCEnumValueIndex solana__storage__confirmed_block__reward_type__enum_values_by_name[5] =
{
  { "Fee", 1 },
  { "Rent", 2 },
  { "Staking", 3 },
  { "Unspecified", 0 },
  { "Voting", 4 },
};
const ProtobufCEnumDescriptor solana__storage__confirmed_block__reward_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "solana.storage.ConfirmedBlock.RewardType",
  "RewardType",
  "Solana__Storage__ConfirmedBlock__RewardType",
  "solana.storage.ConfirmedBlock",
  5,
  solana__storage__confirmed_block__reward_type__enum_values_by_number,
  5,
  solana__storage__confirmed_block__reward_type__enum_values_by_name,
  1,
  solana__storage__confirmed_block__reward_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
